services:
    artifacts:
        environment:
            - BZD_AUTHENTICATION_PRIVATE_KEY
            - BZD_AUTHENTICATION_USERNAME
            - BZD_AUTHENTICATION_PASSWORD
        image: blaizard/artifacts:latest
        ports:
            - 80:8080
        restart: unless-stopped
    bridge:
        image: blaizard/bridge:latest
        ports:
            - 443:1194
            - "2222:22"
        restart: unless-stopped
    watchtower:
        command:
            - --cleanup
            - --include-stopped
            - --interval=3600
            - bridge
            - artifacts
        container_name: watchtower
        image: containrrr/watchtower:latest
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /etc/localtime:/etc/localtime:ro
version: "3.0"
