load("//tools/bazel_build/rules:cc.bzl", "bzd_cc_test")

bzd_cc_test(
    name = "regexp",
    srcs = [
        "regexp.cc",
    ],
    deps = [
        "//cc/bzd/test",
        "//cc/bzd/utility/regexp",
    ],
)
