load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "logging",
    srcs = [
        "__init__.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//bzd/logging/handler",
    ],
)
