load("@bzd_lib//embed:defs.bzl", "bzd_embed")

bzd_embed(
    name = "request_http1.1_chunked",
    format = "cc-include",
    input = "request_http1.1_chunked.txt",
    output = "request_http1.1_chunked.hh",
    visibility = ["//cc/libs/http/tests:__pkg__"],
)
