load("//tools/bazel_build/rules:documentation.bzl", "doc_library")

doc_library(
    name = "bdl",
    srcs = [
        ("Overview", "overview.md"),
        ("Syntax", "syntax.md"),
        ("Components", "components.md"),
        ("Composition", "composition.md"),
        ("Executors", "executors.md"),
        ("Gateway", "gateway.md"),
        ("System", "system.md"),
    ],
    visibility = ["//docs:__pkg__"],
)
