load("@bzd_rules_nodejs//nodejs:defs.bzl", "bzd_nodejs_extern_binary")

bzd_nodejs_extern_binary(
    name = "mocha",
    binary = "mocha/bin/mocha.js",
    packages = {
        "mocha": "10.2.0",
    },
    visibility = ["//visibility:public"],
)
