load("//tools/bazel_build/rules:bdl.bzl", "bzd_manifest")

# ---- Interfaces ----

bzd_manifest(
    name = "channel",
    srcs = [
        "channel.bdl",
    ],
    visibility = ["//visibility:public"],
)
