cc_library(
    name = "ipv4",
    hdrs = [
        "ipv4.hh"
    ],
    srcs = [
        "ipv4.cc"
    ],
    visibility = [
        "//visibility:public"
    ],
    deps = [
        "//cc/bzd/container:result",
        "//cc/bzd/core:error"
    ]
)
