load("@bzd_toolchain_nodejs//nodejs:defs.bzl", "bzd_nodejs_extern_binary")

bzd_nodejs_extern_binary(
    name = "mocha",
    binary = "mocha/bin/mocha",
    packages = {
        "mocha": "",
    },
    visibility = ["//visibility:public"],
)
