load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "validation",
    srcs = [
        "validation.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//python:bzd",
    ],
)
