load("@bzd_python//:defs.bzl", "bzd_python_hermetic_launcher")
load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary")

exports_files([
    "config.job_executor.json",
])

py_binary(
    name = "dyson_fetch",
    srcs = [
        "dyson_fetch.py",
    ],
    deps = [
        requirement("paho-mqtt"),
        "//apps/artifacts/api/python/node",
    ],
)

bzd_python_hermetic_launcher(
    name = "hermetic",
    binary = ":dyson_fetch",
    visibility = [
        "//apps/job_executor:__subpackages__",
        "//deployment:__subpackages__",
    ],
)
