load("//tools/bazel_build/rules:cc.bzl", "bzd_cc_test")

bzd_cc_test(
    name = "regexpr",
    srcs = [
        "regexpr.cc",
    ],
    deps = [
        "//cc/bzd/test",
        "//cc/bzd/utility/regexpr",
    ],
)
