load("//tools/bazel_build/rules:nodejs.bzl", "bzd_nodejs_library")

bzd_nodejs_library(
    name = "scenario",
    srcs = [
        "scenario.mjs",
    ],
    visibility = ["//visibility:public"],
)

bzd_nodejs_library(
    name = "filesystem",
    srcs = [
        "filesystem.mjs",
    ],
    visibility = ["//visibility:public"],
)
