load("@bzd_bdl//:defs.bzl", "bdl_target")
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "main",
    srcs = [
        "main.rs",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//rust/libs/std",
    ],
)

bdl_target(
    name = "auto",
    composition = [
        "composition.bdl",
    ],
    data = {
        "deps": [
            "@crates//:embassy-executor",
            "@crates//:static_cell",
        ],
        "main": [
            "embassy.rs",
        ],
    },
    language = "rust",
    visibility = ["//visibility:public"],
)
