load("@bzd_rules_nodejs//nodejs:defs.bzl", "bzd_nodejs_web_binary")

bzd_nodejs_web_binary(
    name = "serverless",
    srcs = [
        "app.js",
        "app.vue",
    ],
    apis = [
        "//apps/accounts/backend/users:api.json",
    ],
    config_scss = "//nodejs/styles:default.scss",
    main = "app.js",
    deps = [
        "//apps/accounts/authentication:client",
        "//apps/accounts/example:config_nodejs",
        "//nodejs/vue:authentication",
        "//nodejs/vue:rest",
    ],
)
