dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - g++
      - python

git:
  submodules: false

jobs:
  include:
    - name: Production
      script:
      - cp tools/ci/travis/.bazelrc.local .bazelrc.local
      - ./tools/bazel test ... --output_groups=default,metadata --config=prod

    - name: Development
      script:
      - cp tools/ci/travis/.bazelrc.local .bazelrc.local
      - ./tools/bazel test ... --output_groups=default,metadata --config=dev

    - name: linux_x86_64_clang
      script:
      - cp tools/ci/travis/.bazelrc.local .bazelrc.local
      - ./tools/bazel test ... --output_groups=default,metadata --config=linux_x86_64_clang --platform_suffix=_linux_x86_64_clang

    - name: esp32_xtensa_lx6_gcc
      script:
      - cp tools/ci/travis/.bazelrc.local .bazelrc.local
      - ./tools/bazel build ... --output_groups=default,metadata --config=esp32_xtensa_lx6_gcc --platform_suffix=_esp32_xtensa_lx6_gcc

    - name: Sanitizer
      script:
      - cp tools/ci/travis/.bazelrc.local .bazelrc.local
      - ./tools/bazel test ... --config=linux_x86_64_clang --config=sanitizer --config=asan --config=lsan --platform_suffix=_clang_asan_lsan

    - name: Sanitizer Script
      script:
      - cp tools/ci/travis/.bazelrc.local .bazelrc.local
      - ./sanitize.sh
