dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - g++

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/3.0.0/bazel_3.0.0-linux-x86_64.deb
  - sudo dpkg -i bazel_3.0.0-linux-x86_64.deb

script:
  - bazel test ...
