dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - g++
      - python

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel_3.1.0-linux-x86_64.deb
  - sudo dpkg -i bazel_3.1.0-linux-x86_64.deb

jobs:
  include:
    - name: Production
      script:
      - cp tools/ci/travis/.bazelrc.local .bazelrc.local
      - bazel test ... --config=prod --runs_per_test=10

    - name: Development
      script:
      - cp tools/ci/travis/.bazelrc.local .bazelrc.local
      - bazel test ... --config=dev --runs_per_test=10

    - name: linux_x86_64_clang
      script:
      - cp tools/ci/travis/.bazelrc.local .bazelrc.local
      - bazel test ... --config=linux_x86_64_clang --platform_suffix=_linux_x86_64_clang

    - name: esp32_xtensa_lx6_gcc
      script:
      - cp tools/ci/travis/.bazelrc.local .bazelrc.local
      - bazel build ... --config=esp32_xtensa_lx6_gcc --platform_suffix=_esp32_xtensa_lx6_gcc

    - name: Sanitizer
      script:
      - cp tools/ci/travis/.bazelrc.local .bazelrc.local
      - bazel test ... --config=linux_x86_64_clang --config=sanitizer --config=asan --config=lsan --platform_suffix=_clang_asan_lsan
