dist: focal

addons:
    apt:
        packages:
            - wget
            - pkg-config
            - python

git:
    submodules: false

jobs:
    include:
        - name: "Environment"
          script:
              - cp tools/ci/travis/.bazelrc.local .bazelrc.local
              - ./info.sh

        - name: "[normal] static analysis"
          script:
              - cp tools/ci/travis/.bazelrc.local .bazelrc.local
              - ./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --output_groups=+metadata --config=dev --config=clang-tidy --config=mypy --platform_suffix=static_analysis

        - name: "[normal] clang prod"
          script:
              - cp tools/ci/travis/.bazelrc.local .bazelrc.local
              - ./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --output_groups=+metadata --config=clang --config=prod --config=cc --platform_suffix=clang-prod

        - name: "[normal] gcc prod"
          script:
              - cp tools/ci/travis/.bazelrc.local .bazelrc.local
              - ./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --output_groups=+metadata --config=gcc --config=prod --config=cc --platform_suffix=gcc-prod

        - name: "[sanitizer] sanitizer"
          script:
              - cp tools/ci/travis/.bazelrc.local .bazelrc.local
              - ./tools/bazel run :sanitizer -- --check --all
