dist: focal

addons:
  apt:
    packages:
      - wget
      - pkg-config
      - python

git:
  submodules: false

jobs:
  include:
    - name: info
      script:
      - cp tools/ci/travis/.bazelrc.local .bazelrc.local
      - ./info.sh

    - name: linux_x86_64_clang Production
      script:
      - cp tools/ci/travis/.bazelrc.local .bazelrc.local
      - ./tools/bazel test ... --output_groups=default,metadata --config=linux_x86_64_clang --config=prod --platform_suffix=_linux_x86_64_clang_prod

    - name: linux_x86_64_clang Development
      script:
      - cp tools/ci/travis/.bazelrc.local .bazelrc.local
      - ./tools/bazel test ... --output_groups=default,metadata --config=linux_x86_64_clang --config=dev --platform_suffix=_linux_x86_64_clang_dev

    - name: linux_x86_64_gcc
      script:
      - cp tools/ci/travis/.bazelrc.local .bazelrc.local
      - ./tools/bazel test ... --output_groups=default,metadata --config=linux_x86_64_gcc --config=cc --platform_suffix=_linux_x86_64_gcc

    - name: esp32_xtensa_lx6_gcc
      script:
      - cp tools/ci/travis/.bazelrc.local .bazelrc.local
      - ./tools/bazel build ... --output_groups=default,metadata --config=esp32_xtensa_lx6_gcc --config=cc --platform_suffix=_esp32_xtensa_lx6_gcc

    - name: Sanitizer
      script:
      - cp tools/ci/travis/.bazelrc.local .bazelrc.local
      - ./tools/bazel test ... --config=linux_x86_64_clang --config=cc --config=sanitizer --config=asan --config=lsan --platform_suffix=_clang_asan_lsan

    - name: Sanitizer Script
      script:
      - cp tools/ci/travis/.bazelrc.local .bazelrc.local
      - ./sanitize.sh
