matrix:
  include:
   - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - bazel

before_install:
  - ./quality_gate.sh
