#!/bin/bash

# Do not modify, this file has been generated by //tools/ci

set -e

EXTRA_FLAGS="$@"

echo  "==== [normal] static analysis ==============================="
./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --output_groups=+metadata --config=dev --config=clang-tidy --config=mypy --config=clippy $EXTRA_FLAGS
echo  "==== [normal] clang prod ==============================="
./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --output_groups=+metadata --config=clang --config=prod --config=cc $EXTRA_FLAGS
echo  "==== [normal] gcc prod ==============================="
./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --output_groups=+metadata --config=gcc --config=prod --config=cc $EXTRA_FLAGS
echo  "==== [normal] esp32 prod ==============================="
./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --output_groups=+metadata --config=esp32_qemu --config=prod --config=cc $EXTRA_FLAGS
./tools/bazel test //rust/... --output_groups=+metadata --config=esp32_qemu --config=prod --platform_suffix=esp32-prod $EXTRA_FLAGS
echo  "==== [normal] esp32s3 prod ==============================="
./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --output_groups=+metadata --config=esp32s3_qemu --config=prod --config=cc $EXTRA_FLAGS
echo  "==== [stress] dev (100 runs) ==============================="
./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --build_tests_only --test_tag_filters=stress,-cc-coverage --config=dev --runs_per_test=100 --local_test_jobs=1 $EXTRA_FLAGS
echo  "==== [stress] prod (100 runs) ==============================="
./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --build_tests_only --test_tag_filters=stress,-cc-coverage --config=prod --runs_per_test=100 --local_test_jobs=1 $EXTRA_FLAGS
echo  "==== [sanitizer] asan/lsan/ubsan ==============================="
./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --config=clang --config=cc --config=sanitizer --config=asan --config=lsan --config=ubsan $EXTRA_FLAGS
echo  "==== [sanitizer] tsan ==============================="
./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --config=clang --config=cc --config=sanitizer --config=tsan $EXTRA_FLAGS
echo  "==== [coverage] cc ==============================="
./tools/bazel coverage cc/... --config=gcc --config=cc --config=local $EXTRA_FLAGS
echo  "==== [coverage] nodejs ==============================="
./tools/bazel coverage ... --config=nodejs --config=local $EXTRA_FLAGS
echo  "==== [sanitizer] sanitizer ==============================="
./tools/bazel run :sanitizer -- --check --all $EXTRA_FLAGS
