py_library(
    name = "extract_compiler_cmd",
    srcs = ["extract_compiler_cmd.py"],
	visibility = ["//visibility:public"],
)

py_binary(
    name = "terminal",
    srcs = ["terminal.py"],
	visibility = ["//visibility:public"],
)
