load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "extract_compiler_cmd",
    srcs = ["extract_compiler_cmd.py"],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "web_server",
    srcs = ["web_server.py"],
    visibility = ["//visibility:public"],
)
