load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

exports_files([
    "package.bzl",
])

bzl_library(
    name = "package",
    srcs = [
        "defs.bzl",
    ],
    visibility = ["//visibility:public"],
)
