load("//tools/bazel_build/rules:cc.bzl", "bzd_cc_test")

bzd_cc_test(
    name = "non_null_ptr",
    srcs = [
        "non_null_ptr.cc",
    ],
    deps = [
        "//cc/bzd/test",
        "//cc/bzd/utility/memory:non_null_ptr",
    ],
)
