load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "xthal_clock",
    hdrs = [
        "xthal_clock.hh",
    ],
    srcs = [
        "xthal_clock.cc",
    ],
    tags = ["manual"],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/core:clock",
    ],
)
