load("//tools/bazel_build/rules:cc.bzl", "cc_library")

cc_library(
    name = "panic",
    srcs = [
        "panic.cc",
    ],
    hdrs = [
        "//cc/bzd/core:panic.hh",
    ],
    visibility = ["//visibility:public"],
)
