objects:
    bzd::OChannel.i2c:
        config:
            frequency: 100000
            interface: 0
            mode: !ref 'Mode::MASTER'
            scl: 22
            sda: 21
        implementation: !ref 'bzd::io::I2C'
    bzd::OChannel.led:
        implementation: !ref 'bzd::io::DigitalOutput'
        params:
        - 2
