load("//cc/bdl:cc.bzl", "bzd_cc_test")

bzd_cc_test(
    name = "tests",
    srcs = [
        "client.cc",
    ],
    deps = [
        "//cc:bzd",
        "//cc/bdl/generator/impl/adapter:context",
        "//cc/bzd/test",
        "//cc/components/generic/network/tcp:client",
    ],
)
