load("@bzd_rules_nodejs//nodejs:defs.bzl", "bzd_nodejs_requirements_compile")

bzd_nodejs_requirements_compile(
    name = "requirements",
    srcs = [
        "requirements.in",
    ],
    output_path = "tools/bazel_build/modules/bzd_bdl/diagram/requirements/requirements.json",
)
