load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "non_owning",
    hdrs = [
        "non_owning.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/platform:types",
    ],
)

cc_library(
    name = "resizeable",
    hdrs = [
        "resizeable.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/platform:types",
    ],
)

cc_library(
    name = "fixed",
    hdrs = [
        "fixed.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/platform:types",
    ],
)
