cc_library(
	name = "non_owning",
	hdrs = [
		"non_owning.h",
	],
    visibility = ["//visibility:public"],
	deps = [
		"//cc/bzd/platform:types",
	]
)

cc_library(
	name = "resizeable",
	hdrs = [
		"resizeable.h",
	],
    visibility = ["//visibility:public"],
	deps = [
		"//cc/bzd/platform:types",
	]
)

cc_library(
	name = "fixed",
	hdrs = [
		"fixed.h",
	],
    visibility = ["//visibility:public"],
	deps = [
		"//cc/bzd/platform:types",
	]
)
