load("//tools/bazel.build/rules:nodejs.bzl", "bzd_nodejs_library")

bzd_nodejs_library(
    name = "default",
    alias = "bzd-style",
    srcs = glob([
        "**/*",
    ]),
    visibility = ["//visibility:public"],
)
