py_library(
    name = "factory",
    srcs = [
        "factory.py"
    ],
    deps = [
        "//tools/shell:factory",
    ],
    data = glob(
        [
            "srcs/**/*",
        ],
    ),
    visibility = [
        "//tools/shell:__pkg__",
    ],
)
