load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "client",
    srcs = ["client.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "server",
    srcs = ["server.py"],
    visibility = ["//visibility:public"],
)
