load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "parser",
    srcs = glob(["*.py"]),
    visibility = ["//tools/bazel_build/rules/assets/cc/map_analyzer:__subpackages__"],
)
