load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "wifi",
    srcs = [
        "main.cc",
    ],
    tags = ["manual"],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd",
    ],
)
