package(default_visibility = ["//visibility:public"])

platform(
    name = "linux_x86_64",
    constraint_values = [
        "//tools/bazel.build/target/al:linux",
        "//tools/bazel.build/target/isa:x86_64",
    ],
)
