filegroup(
    name = "package_json_template",
    srcs = ["package.json.template"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "webpack_config_template",
    srcs = ["webpack.config.cjs.template"],
    visibility = ["//visibility:public"],
)
