load("@bzd_rules_nodejs//nodejs:defs.bzl", "bzd_nodejs_binary", "bzd_nodejs_web_binary")

bzd_nodejs_web_binary(
    name = "frontend",
    srcs = [
        "frontend.js",
        "frontend.vue",
    ],
    apis = [
        "//apps/accounts/backend/users:api.json",
    ],
    config_scss = "//nodejs/styles:default.scss",
    main = "frontend.js",
    deps = [
        "//apps/accounts/authentication:client",
        "//apps/accounts/example:config_nodejs",
        "//nodejs/vue:authentication",
        "//nodejs/vue:rest",
    ],
)

bzd_nodejs_binary(
    name = "server",
    srcs = [
        "backend.js",
    ],
    args = [
        "$(rootpath :frontend.bundle)",
    ],
    data = [
        ":frontend.bundle",
    ],
    main = "backend.js",
    deps = [
        "//apps/accounts/authentication:server",
        "//apps/accounts/example:config_nodejs",
        "//nodejs/core/http:server",
        "//nodejs/core/rest:server",
    ],
)
