load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "throw",
    srcs = [
        "throw.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/platform:panic",
    ],
)
