load("//tools/bazel_build/rules:bdl.bzl", "bdl_library")

bdl_library(
    name = "backend",
    srcs = [
        "logger.bdl",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/core:channel3",
    ],
)
