load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "support",
    hdrs = [
        "support.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/platform:types",
        "//cc/bzd/utility:move",
    ],
)
