load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "steady_clock",
    hdrs = [
        "steady_clock.hh",
    ],
    srcs = [
        "steady_clock.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/core:clock",
    ],
)
