load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "info_script",
    srcs = glob([
        "*.py",
    ]),
    main = "info_script.py",
	visibility = ["//visibility:public"],
)
