name: CI

on:
    push: {}

jobs:
    build:
        runs-on: linux

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "true"

            - name: "Enable Remote Execution"
              run: |
                  ./tools/bazel run //deployment:remote_wol --config=local

            - name: "Environment"
              run: |
                  cp tools/ci/gitea/.bazelrc.local .bazelrc.local
                  ./info.sh

            - name: "Build Tools"
              run: |
                  mkdir bin
                  ./tools/bazel build //tools/ci:timeit --//apps/artifacts/api:config.set=remotes=https://datalocal.blaizard.com
                  cp bazel-bin/tools/ci/timeit bin/timeit

            - name: "[normal] static analysis"
              run: |
                  ./bin/timeit --path gitea/static_analysis/command-0 \
                  ./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --output_groups=+metadata --config=dev --config=clang-tidy --config=mypy --platform_suffix=static_analysis

            - name: "[normal] clang prod"
              run: |
                  ./bin/timeit --path gitea/clang_prod/command-0 \
                  ./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --output_groups=+metadata --config=clang --config=prod --config=cc --platform_suffix=clang-prod

            - name: "[normal] gcc prod"
              run: |
                  ./bin/timeit --path gitea/gcc_prod/command-0 \
                  ./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --output_groups=+metadata --config=gcc --config=prod --config=cc --platform_suffix=gcc-prod

            - name: "[normal] esp32 prod"
              run: |
                  ./bin/timeit --path gitea/esp32_prod/command-0 \
                  ./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --output_groups=+metadata --config=esp32 --config=prod --config=cc --platform_suffix=esp32-prod

            - name: "[stress] dev (10 runs)"
              run: |
                  ./bin/timeit --path gitea/dev_10_runs_/command-0 \
                  ./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --build_tests_only --test_tag_filters=stress,-cc-coverage --config=dev --runs_per_test=10 --local_test_jobs=1 --platform_suffix=stress-dev

            - name: "[stress] prod (10 runs)"
              run: |
                  ./bin/timeit --path gitea/prod_10_runs_/command-0 \
                  ./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --build_tests_only --test_tag_filters=stress,-cc-coverage --config=prod --runs_per_test=10 --local_test_jobs=1 --platform_suffix=stress-prod

            - name: "[sanitizer] asan/lsan/ubsan"
              run: |
                  ./bin/timeit --path gitea/asan_lsan_ubsan/command-0 \
                  ./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --config=clang --config=cc --config=sanitizer --config=asan --config=lsan --config=ubsan --platform_suffix=clang-asan-lsan-ubsan

            - name: "[sanitizer] tsan"
              run: |
                  ./bin/timeit --path gitea/tsan/command-0 \
                  ./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --config=clang --config=cc --config=sanitizer --config=tsan --platform_suffix=clang-tsan

            - name: "[coverage] NodeJs"
              run: |
                  ./bin/timeit --path gitea/NodeJs/command-0 \
                  ./tools/bazel coverage ... --config=nodejs --platform_suffix=coverage-nodejs --config=local
                  ./bin/timeit --path gitea/NodeJs/command-1 \
                  ./tools/bazel run @bzd_coverage//:coverage --platform_suffix=coverage-nodejs --config=local -- --output bazel-out/coverage-nodejs

            - name: "[sanitizer] sanitizer"
              run: |
                  ./bin/timeit --path gitea/sanitizer/command-0 \
                  ./tools/bazel run :sanitizer -- --check --all

            - name: "Deploy"
              uses: https://git.blaizard.com/blaise/deployment@main
              with:
                  ssh_private_key: ${{ secrets.BZD_SSH_PRIVATE_KEY }}
                  digitalocean_api_token: ${{ secrets.BZD_DIGITALOCEAN_API_TOKEN }}

            - name: "Info"
              if: always()
              run: |
                  ./info.sh

            - name: "Disable Remote Execution"
              if: always()
              run: |
                  ./tools/bazel run //deployment:remote_suspend --config=local
