name: CI

on:
    push: {}

jobs:
    build:
        runs-on: linux

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "true"

            - name: "Environment"
              run: |
                  cp tools/ci/gitea/.bazelrc.local .bazelrc.local
                  ./info.sh

            - uses: ./deployment/docker.blaizard.com

            - uses: ./deployment/accounts.blaizard.com
              with:
                docker_api_token: ${{ secrets.BZD_DIGITALOCEAN_API_TOKEN }}

            - name: "Info"
              if: always()
              run: |
                  ./info.sh

            - name: "Disable Remote Execution"
              if: always()
              run: |
                  ./tools/bazel run //apps/node_manager:client --config=local -- suspend 10.10.0.10:8000
