name: CI

on:
    push: {}

jobs:
    build:
        runs-on: linux

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "true"

            - name: "Enable Remote Execution"
              run: |
                  ./tools/bazel run //apps/node_manager:client --config=local -- wol --wait 10.10.0.11:8980 --broadcast 10.10.0.255 --timeout 300 08:bf:b8:14:04:b6

            - name: "Environment"
              run: |
                  cp tools/ci/gitea/.bazelrc.local .bazelrc.local
                  ./info.sh

            - name: "[normal] python"
              run: |
                  ./tools/bazel test @bzd_python//... --output_groups=+metadata --config=prod --platform_suffix=python

            - name: "[normal] clang-tidy"
              run: |
                  ./tools/bazel test ... --output_groups=+metadata --config=dev --config=clang-tidy --platform_suffix=clang-tidy

            - name: "[normal] clang prod"
              run: |
                  ./tools/bazel test ... --output_groups=+metadata --config=clang --config=prod --config=cc --platform_suffix=clang-prod

            - name: "[normal] gcc prod"
              run: |
                  ./tools/bazel test ... --output_groups=+metadata --config=gcc --config=prod --config=cc --platform_suffix=gcc-prod

            - name: "[normal] esp32 prod"
              run: |
                  ./tools/bazel test ... --output_groups=+metadata --config=esp32 --config=prod --config=cc --platform_suffix=esp32-prod

            - name: "[stress] dev (10 runs)"
              run: |
                  ./tools/bazel test ... --build_tests_only --test_tag_filters=stress,-cc-coverage --config=dev --runs_per_test=10 --platform_suffix=stress-dev

            - name: "[stress] prod (10 runs)"
              run: |
                  ./tools/bazel test ... --build_tests_only --test_tag_filters=stress,-cc-coverage --config=prod --runs_per_test=10 --platform_suffix=stress-prod

            - name: "[sanitizer] asan/lsan/ubsan"
              run: |
                  ./tools/bazel test ... --config=clang --config=cc --config=sanitizer --config=asan --config=lsan --config=ubsan --platform_suffix=clang-asan-lsan-ubsan

            - name: "[sanitizer] tsan"
              run: |
                  ./tools/bazel test ... --config=clang --config=cc --config=sanitizer --config=tsan --platform_suffix=clang-tsan

            - name: "[coverage] NodeJs"
              run: |
                  ./tools/bazel coverage ... --config=nodejs --platform_suffix=coverage-nodejs --config=local
                  ./tools/bazel run tools/coverage --platform_suffix=coverage-nodejs --config=local -- --output bazel-out/coverage-nodejs

            - name: "[sanitizer] sanitizer"
              run: |
                  ./tools/bazel run :sanitizer -- --check --all


            - uses: ./deployment/docker.blaizard.com

            - uses: ./deployment/accounts.blaizard.com
              with:
                docker_api_token: ${{ secrets.BZD_DIGITALOCEAN_API_TOKEN }}

            - name: "Info"
              if: always()
              run: |
                  ./info.sh

            - name: "Disable Remote Execution"
              if: always()
              run: |
                  ./tools/bazel run //apps/node_manager:client --config=local -- suspend 10.10.0.10:8000
