name: CI

on:
    push: {}

jobs:
    build:
        runs-on: linux

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "true"

            - name: "Enable Remote Execution"
              run: |
                  ./tools/bazel run //deployment:remote_wol --config=local

            - name: "Environment"
              run: |
                  cp tools/ci/gitea/.bazelrc.local .bazelrc.local
                  ./info.sh

            - name: "Deploy"
              uses: https://git.blaizard.com/blaise/deployment@main
              with:
                  ssh_private_key: ${{ secrets.BZD_SSH_PRIVATE_KEY }}
                  digitalocean_api_token: ${{ secrets.BZD_DIGITALOCEAN_API_TOKEN }}

            - name: "Info"
              if: always()
              run: |
                  ./info.sh

            - name: "Disable Remote Execution"
              if: always()
              run: |
                  ./tools/bazel run //deployment:remote_suspend --config=local
