name: CI

on:
    push: {}

jobs:
    build:
        runs-on: linux

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "true"

            - name: "Environment"
              run: |
                  cp tools/ci/gitea/.bazelrc.local .bazelrc.local

            - name: "Custom action"
              uses: https://git.blaizard.com/blaise/bzd/.gitea/actions/hello

            - name: "Info"
              if: always()
              run: |
                  ./info.sh
