name: CI

on:
    push: {}

jobs:
    build:
        runs-on: linux

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "true"

            - name: "Deploy"
              uses: https://git.blaizard.com/blaise/deployment@main
              secrets:
                  digitalocean_api_token: ${{ secrets.BZD_DIGITALOCEAN_API_TOKEN }}
                  test_var: ${{ secrets.BZD_TEST }}

            - name: "Info"
              if: always()
              run: |
                  ./info.sh
