name: Nix Build

on:
    workflow_dispatch: # allows manual triggering

jobs:
    lease_linux:
        runs-on: node_manager_client
        steps:
            - name: "Lease Linux"
              uses: https://git.blaizard.com/blaise/deployment/ci/gitea/lease_linux@main
              with:
                  name: "nix_build"
                  ttl: "300"

    build_linux:
        needs: lease_linux
        runs-on: linux
        steps:
            - uses: https://git.blaizard.com/blaise/deployment/ci/gitea/setup@main
              with:
                  lease: "true"

            - name: "Install Nix"
              run: |
                  bzd-lease sudo bash -c '
                      set -euo pipefail
                      curl -sSfL https://artifacts.nixos.org/nix-installer | sh -s -- install linux --enable-flakes --no-confirm --init none
                  '

            - name: "Set the SSH key"
              uses: https://git.blaizard.com/blaise/bzd/.gitea/actions/ssh_key@master
              with:
                  ssh_private_key: ${{ secrets.BZD_NIXOS_CACHE_SSH_KEY }}

            - name: "Build"
              run: |
                  bzd-lease sudo bash -c '
                      export PATH="/root/.nix-profile/bin:/nix/var/nix/profiles/default/bin:$PATH"
                      ./deployment/nixos/provision.py --node beast-llm --cache beast-nixos-cache build
                  '
