name: Test

on:
    workflow_dispatch: # allows manual triggering

jobs:
    lease_linux:
        runs-on: node_manager_client
        steps:
            - name: "Lease Linux"
              uses: https://git.blaizard.com/blaise/deployment/ci/gitea/lease_linux@main
              with:
                  name: "ci"
                  ttl: "300"

    build_linux:
        needs: lease_linux
        runs-on: linux
        steps:
            - uses: https://git.blaizard.com/blaise/deployment/ci/gitea/setup@main
              with:
                  lease: "true"
                  node: "true"

            - name: "Info"
              run: |
                  ./info.sh
