version: 2.0
jobs:
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: apt-get install ncurses-compat-libs
      - run: ./tools/bazel.build/setup_bazel.sh 
      - run: ./quality_gate.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest
