load("@rules_python//python:defs.bzl", "py_binary")
load("//private/write_file:write_file.bzl", "bzd_write_file")

bzd_write_file(
    name = "config.py",
    content = """
age = "{age}"
recipients = "{recipients}"
""",
    data = [
        "@age",
        "@secrets//:recipients.json",
    ],
    substitutions = {
        "{age}": "$(rlocationpath @age//:age)",
        "{recipients}": "$(rlocationpath @secrets//:recipients.json)",
    },
)

py_binary(
    name = "secret",
    srcs = [
        "secret.py",
        ":config.py",
    ],
    data = [
        "@age",
        "@secrets//:recipients.json",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@bzd_python//bzd/utils:runfiles",
    ],
)
