load("@rules_python//python:defs.bzl", "py_binary")
load("//config:defs.bzl", "bzd_config")

bzd_config(
    name = "config",
    data = [
        "@age",
        "@secrets//:recipients.json",
    ],
    values = {
        "age": "$(rlocationpath @age//:age)",
        "recipients": "$(rlocationpath @secrets//:recipients.json)",
    },
    visibility = ["//nodejs:__pkg__"],
)

py_binary(
    name = "secret",
    srcs = [
        "secret.py",
        ":config.py",
    ],
    data = [
        ":config",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "@rules_python//python/runfiles",
    ],
)
