load("@bzd_rules_nodejs//nodejs:defs.bzl", "bzd_nodejs_library")

bzd_nodejs_library(
    name = "array",
    srcs = [
        "array.ts",
    ],
    visibility = ["//visibility:public"],
)

bzd_nodejs_library(
    name = "color",
    srcs = [
        "color.ts",
        "//nodejs/utils/impl/color:backend.ts",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//nodejs/core:exception",
    ],
)

bzd_nodejs_library(
    name = "delay",
    srcs = [
        "delay.ts",
    ],
    visibility = ["//visibility:public"],
)

bzd_nodejs_library(
    name = "object",
    srcs = [
        "object.ts",
    ],
    visibility = ["//visibility:public"],
)

bzd_nodejs_library(
    name = "optional",
    srcs = [
        "optional.ts",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//nodejs/core:exception",
    ],
)

bzd_nodejs_library(
    name = "query",
    srcs = [
        "query.ts",
    ],
    visibility = ["//visibility:public"],
)

bzd_nodejs_library(
    name = "pathlib",
    srcs = [
        "pathlib.ts",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//nodejs/core:exception",
    ],
)

bzd_nodejs_library(
    name = "run",
    srcs = [
        "run.js",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//nodejs/core:event",
        "//nodejs/core:exception",
    ],
)

bzd_nodejs_library(
    name = "to_string",
    srcs = [
        "to_string.js",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//nodejs/core:exception",
        "//nodejs/core:format",
    ],
)

bzd_nodejs_library(
    name = "uid",
    srcs = [
        "uid.js",
    ],
    visibility = ["//visibility:public"],
)

bzd_nodejs_library(
    name = "regexpr",
    srcs = [
        "regexpr.ts",
    ],
    visibility = ["//visibility:public"],
)

bzd_nodejs_library(
    name = "result",
    srcs = [
        "result.ts",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//nodejs/core:exception",
        "//nodejs/core:format",
    ],
)

bzd_nodejs_library(
    name = "timestamp",
    srcs = [
        "timestamp.js",
    ],
    visibility = ["//visibility:public"],
)
