load("@bzd_lib//:defs.bzl", "bzd_write_file")
load("@bzd_rules_nodejs//nodejs:defs.bzl", "bzd_nodejs_library")

bzd_write_file(
    name = "config.ts",
    content = """
export const age: string = "{age}";
""",
    data = [
        "@age",
    ],
    substitutions = {
        "{age}": "$(rlocationpath @age//:age)",
    },
)

bzd_nodejs_library(
    name = "secret",
    srcs = [
        "config.ts",
        "secret.ts",
    ],
    data = [
        "@age",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":runfiles",
    ],
)

bzd_nodejs_library(
    name = "runfiles",
    srcs = [
        "runfiles.ts",
    ],
    visibility = ["//visibility:public"],
)

bzd_nodejs_library(
    name = "array",
    srcs = [
        "array.ts",
    ],
    visibility = ["//visibility:public"],
)

bzd_nodejs_library(
    name = "color",
    srcs = [
        "color.ts",
        "//nodejs/utils/impl/color:backend.ts",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//nodejs/core:exception",
    ],
)

bzd_nodejs_library(
    name = "delay",
    srcs = [
        "delay.ts",
    ],
    visibility = ["//visibility:public"],
)

bzd_nodejs_library(
    name = "object",
    srcs = [
        "object.ts",
    ],
    visibility = ["//visibility:public"],
)

bzd_nodejs_library(
    name = "optional",
    srcs = [
        "optional.ts",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//nodejs/core:exception",
    ],
)

bzd_nodejs_library(
    name = "query",
    srcs = [
        "query.ts",
    ],
    visibility = ["//visibility:public"],
)

bzd_nodejs_library(
    name = "pathlib",
    srcs = [
        "pathlib.ts",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//nodejs/core:exception",
    ],
)

bzd_nodejs_library(
    name = "run",
    srcs = [
        "run.ts",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//nodejs/core:event",
        "//nodejs/core:exception",
    ],
)

bzd_nodejs_library(
    name = "to_string",
    srcs = [
        "to_string.ts",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//nodejs/core:exception",
        "//nodejs/core:format",
    ],
)

bzd_nodejs_library(
    name = "uid",
    srcs = [
        "uid.ts",
    ],
    visibility = ["//visibility:public"],
)

bzd_nodejs_library(
    name = "regexpr",
    srcs = [
        "regexpr.ts",
    ],
    visibility = ["//visibility:public"],
)

bzd_nodejs_library(
    name = "result",
    srcs = [
        "result.ts",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//nodejs/core:exception",
        "//nodejs/core:format",
    ],
)

bzd_nodejs_library(
    name = "timestamp",
    srcs = [
        "timestamp.ts",
    ],
    visibility = ["//visibility:public"],
)
