package(default_visibility = ["//visibility:public"])

constraint_setting(
    name = "toolchain",
    default_constraint_value = ":default",
)

constraint_value(
    name = "default",
    constraint_setting = ":toolchain",
)
