load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "echo",
    srcs = [
        "echo.py",
    ],
    visibility = ["//apps/bootloader:__pkg__"],
)

py_binary(
    name = "error",
    srcs = [
        "error.py",
    ],
    visibility = ["//apps/bootloader:__pkg__"],
)

py_binary(
    name = "sleep",
    srcs = [
        "sleep.py",
    ],
    visibility = ["//apps/bootloader:__pkg__"],
)
