cc_library(
	name = "stack",
	hdrs = [
		"stack.h",
	],
	deps = [
		"//cc/bzd/algorithm:fill",
		"//cc/bzd/container:array",
		"//cc/bzd/platform:types",
	],
    visibility = ["//visibility:public"],
)
