load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "stack",
    hdrs = [
        "stack.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/algorithm:fill",
        "//cc/bzd/container:array",
        "//cc/bzd/platform:types",
    ],
)
