load("@bzd_lib//config:defs.bzl", "bzd_config_default")

bzd_config_default(
    name = "bin",
    values = {
        "scp": "scp",
        "ssh": "ssh",
    },
    visibility = ["//bzd:__subpackages__"],
)
