load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "bzd",
    srcs = [
        "lib.rs",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//rust/bzd/test",
    ],
)
