load("@bzd_rules_nodejs//nodejs:defs.bzl", "bzd_nodejs_test")

bzd_nodejs_test(
    name = "array",
    srcs = ["array_test.ts"],
    main = "array_test.ts",
    deps = [
        "//nodejs/core:exception",
        "//nodejs/utils:array",
    ],
)

bzd_nodejs_test(
    name = "to_string",
    srcs = ["to_string_test.ts"],
    main = "to_string_test.ts",
    deps = [
        "//nodejs/core:exception",
        "//nodejs/utils:to_string",
    ],
)

bzd_nodejs_test(
    name = "color",
    srcs = ["color_test.ts"],
    main = "color_test.ts",
    deps = [
        "//nodejs/core:exception",
        "//nodejs/utils:color",
    ],
)

bzd_nodejs_test(
    name = "object",
    srcs = ["object_test.ts"],
    main = "object_test.ts",
    deps = [
        "//nodejs/core:exception",
        "//nodejs/utils:object",
    ],
)

bzd_nodejs_test(
    name = "optional",
    srcs = ["optional_test.ts"],
    main = "optional_test.ts",
    deps = [
        "//nodejs/core:exception",
        "//nodejs/utils:optional",
    ],
)

bzd_nodejs_test(
    name = "pathlib",
    srcs = ["pathlib_test.ts"],
    main = "pathlib_test.ts",
    deps = [
        "//nodejs/core:exception",
        "//nodejs/utils:pathlib",
    ],
)

bzd_nodejs_test(
    name = "regexpr",
    srcs = ["regexpr_test.ts"],
    main = "regexpr_test.ts",
    deps = [
        "//nodejs/core:exception",
        "//nodejs/utils:regexpr",
    ],
)

bzd_nodejs_test(
    name = "result",
    srcs = ["result_test.ts"],
    main = "result_test.ts",
    deps = [
        "//nodejs/core:exception",
        "//nodejs/utils:result",
    ],
)

bzd_nodejs_test(
    name = "run",
    srcs = ["run_test.ts"],
    main = "run_test.ts",
    deps = [
        "//nodejs/core:exception",
        "//nodejs/utils:run",
    ],
)

bzd_nodejs_test(
    name = "timestamp",
    srcs = ["timestamp_test.ts"],
    main = "timestamp_test.ts",
    deps = [
        "//nodejs/core:exception",
        "//nodejs/utils:timestamp",
    ],
)

bzd_nodejs_test(
    name = "uid",
    srcs = ["uid_test.ts"],
    main = "uid_test.ts",
    deps = [
        "//nodejs/core:exception",
        "//nodejs/utils:uid",
    ],
)
