load("//apps/dashboard/plugins:defs.bzl", "bzd_plugins")

bzd_plugins(
    name = "plugins",
    plugins = [
        "//apps/dashboard/plugins/coverage:coverage",
        "//apps/dashboard/plugins/coverage:coverage_report",
        "//apps/dashboard/plugins/continuous_integration:continuous_integration",
        "//apps/dashboard/plugins/github:github",
        "//apps/dashboard/plugins/jenkins:jenkins",
        "//apps/dashboard/plugins/link:link",
        "//apps/dashboard/plugins/travisci:travisci",
    ]
)
