load("//tools/bazel_build/rules:cc.bzl", "cc_library")

cc_library(
    name = "contiguous",
    hdrs = [
        "contiguous.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/platform:types",
    ],
)
