load("@rules_rust//rust:defs.bzl", "rust_library_group")

rust_library_group(
    name = "std",
    target_compatible_with = [
        "@bzd_platforms//al:linux",
    ],
    visibility = ["//visibility:public"],
)
