load("//cc/bdl:cc.bzl", "bzd_cc_test")

bzd_cc_test(
    name = "tests",
    srcs = [
        "integral.cc",
        "pattern.cc",
    ],
    deps = [
        "//cc/bzd/test",
        "//cc/bzd/utility/pattern:from_string",
    ],
)
