load("//apps/dashboard/plugins:defs.bzl", "bzd_plugin")

bzd_plugin(
    name = "coverage_report",
    metadata = "report.mjs",
    backend_entry_point = "source_backend.mjs",
)

bzd_plugin(
    name = "coverage",
    metadata = "coverage.mjs",
    frontend_entry_point = "visualization.vue"
)
