load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "client",
    srcs = [
        "client.py",
    ],
)

py_binary(
    name = "server",
    srcs = [
        "server.py",
    ],
)
