load("//tools/bazel_build/rules:cc.bzl", "bzd_cc_binary")

bzd_cc_binary(
    name = "channel",
    srcs = [
        "main.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc:bzd",
    ],
)
