load("//tools/bazel_build/rules:cc.bzl", "cc_binary")

cc_binary(
    name = "channel",
    srcs = [
        "main.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd",
    ],
)
