load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "timer",
    testonly = True,
    hdrs = ["timer.hh"],
    visibility = [
        "//cc/libs/timer/tests:__pkg__",
    ],
    deps = ["//cc/libs/timer"],
)
