load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "agent_lib",
    srcs = [
        "agent.py",
        "json.py",
    ],
    visibility = [
        "//apps/utils/agent:__subpackages__",
    ],
    deps = [
        "@bzd_python//bzd/utils:run",
    ],
)

py_binary(
    name = "agent",
    srcs = [
        "agent.py",
    ],
    deps = [
        ":agent_lib",
    ],
)
