load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "archive_to_script",
    srcs = [
        "archive_to_script.py",
    ],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "bundler",
    srcs = [
        "bundler.py",
    ],
    visibility = ["//visibility:public"],
)
