filegroup(
    name = "headers",
    srcs = glob([
        "**/*.h",
    ]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "sources",
    srcs = glob([
        "**/*.cpp",
    ]),
    visibility = ["//visibility:public"],
)
