// Note: this file is automatically generated, all modifications will be lost.


export default {
	ad: {
		name: "Andorra",
		timezone: [],
		search: ["principality of andorra", "andorra", "ad", "principat d'andorra", "and"],
		call: ["376"],
		currency: ["eur"],
		lang: ["cat"]
	},
	ae: {
		name: "United Arab Emirates",
		timezone: ["+04:00"],
		search: ["united arab emirates", "دولة الإمارات العربية المتحدة", "ae", "uae", "emirates", "are"],
		call: ["971"],
		currency: ["aed"],
		lang: ["ara"]
	},
	af: {
		name: "Afghanistan",
		timezone: ["+04:30"],
		search: ["islamic republic of afghanistan", "افغانستان", "owganystan", "af", "afġānistān", "afg", "afghanistan"],
		call: ["93"],
		currency: ["afn"],
		lang: ["prs", "pus", "tuk"]
	},
	ag: {
		name: "Antigua and Barbuda",
		timezone: [],
		search: ["antigua and barbuda", "ag", "atg"],
		call: ["1268"],
		currency: ["xcd"],
		lang: ["eng"]
	},
	ai: {
		name: "Anguilla",
		timezone: [],
		search: ["anguilla", "ai", "aia"],
		call: ["1264"],
		currency: ["xcd"],
		lang: ["eng"]
	},
	al: {
		name: "Albania",
		timezone: ["+01:00"],
		search: ["republic of albania", "shqipëria", "al", "shqipëri", "shqipnia", "alb", "albania"],
		call: ["355"],
		currency: ["all"],
		lang: ["sqi"]
	},
	am: {
		name: "Armenia",
		timezone: ["+04:00"],
		search: ["republic of armenia", "հայաստան", "am", "hayastan", "հայաստանի հանրապետություն", "arm", "armenia"],
		call: ["374"],
		currency: ["amd"],
		lang: ["hye"]
	},
	ao: {
		name: "Angola",
		timezone: [],
		search: ["republic of angola", "angola", "ao", "república de angola", "ʁɛpublika de an'ɡɔla", "ago"],
		call: ["244"],
		currency: ["aoa"],
		lang: ["por"]
	},
	aq: { name: "Antarctica", timezone: [], search: ["antarctica", "aq", "ata"], call: [], currency: [], lang: [] },
	ar: {
		name: "Argentina",
		timezone: ["-03:00"],
		search: ["argentine republic", "argentina", "ar", "república argentina", "arg"],
		call: ["54"],
		currency: ["ars"],
		lang: ["grn", "spa"]
	},
	as: {
		name: "American Samoa",
		timezone: [],
		search: ["american samoa", "sāmoa amelika", "as", "amerika sāmoa", "amelika sāmoa", "asm"],
		call: ["1684"],
		currency: ["usd"],
		lang: ["eng", "smo"]
	},
	at: {
		name: "Austria",
		timezone: ["+01:00"],
		search: ["republic of austria", "österreich", "at", "osterreich", "oesterreich", "aut", "austria"],
		call: ["43"],
		currency: ["eur"],
		lang: ["bar"]
	},
	au: {
		name: "Australia",
		timezone: ["+11:00", "+10:00", "+09:30", "+08:00"],
		search: ["commonwealth of australia", "australia", "au", "aus"],
		call: ["61"],
		currency: ["aud"],
		lang: ["eng"]
	},
	aw: {
		name: "Aruba",
		timezone: [],
		search: ["aruba", "aw", "abw"],
		call: ["297"],
		currency: ["awg"],
		lang: ["nld", "pap"]
	},
	ax: {
		name: "Åland Islands",
		timezone: [],
		search: ["åland islands", "åland", "ax", "aaland", "aland", "ahvenanmaa", "ala"],
		call: ["358"],
		currency: ["eur"],
		lang: ["swe"]
	},
	az: {
		name: "Azerbaijan",
		timezone: ["+04:00"],
		search: [
			"republic of azerbaijan",
			"azərbaycan",
			"азербайджан",
			"az",
			"azərbaycan respublikası",
			"aze",
			"azerbaijan"
		],
		call: ["994"],
		currency: ["azn"],
		lang: ["aze", "rus"]
	},
	ba: {
		name: "Bosnia and Herzegovina",
		timezone: ["+01:00"],
		search: [
			"bosnia and herzegovina",
			"bosna i hercegovina",
			"боснa и херцеговина",
			"ba",
			"bosnia-herzegovina",
			"босна и херцеговина",
			"bih"
		],
		call: ["387"],
		currency: ["bam"],
		lang: ["bos", "hrv", "srp"]
	},
	bb: {
		name: "Barbados",
		timezone: [],
		search: ["barbados", "bb", "brb"],
		call: ["1246"],
		currency: ["bbd"],
		lang: ["eng"]
	},
	bd: {
		name: "Bangladesh",
		timezone: ["+06:00"],
		search: ["people's republic of bangladesh", "বাংলাদেশ", "bd", "gônôprôjatôntri bangladesh", "bgd", "bangladesh"],
		call: ["880"],
		currency: ["bdt"],
		lang: ["ben"]
	},
	be: {
		name: "Belgium",
		timezone: ["+01:00"],
		search: [
			"kingdom of belgium",
			"belgien",
			"belgique",
			"belgië",
			"be",
			"belgie",
			"koninkrijk belgië",
			"royaume de belgique",
			"königreich belgien",
			"bel",
			"belgium"
		],
		call: ["32"],
		currency: ["eur"],
		lang: ["deu", "fra", "nld"]
	},
	bf: {
		name: "Burkina Faso",
		timezone: [],
		search: ["burkina faso", "bf", "bfa"],
		call: ["226"],
		currency: ["xof"],
		lang: ["fra"]
	},
	bg: {
		name: "Bulgaria",
		timezone: ["+02:00"],
		search: ["republic of bulgaria", "българия", "bg", "република българия", "bgr", "bulgaria"],
		call: ["359"],
		currency: ["bgn"],
		lang: ["bul"]
	},
	bh: {
		name: "Bahrain",
		timezone: ["+03:00"],
		search: ["kingdom of bahrain", "‏البحرين", "bh", "mamlakat al-baḥrayn", "bhr", "bahrain"],
		call: ["973"],
		currency: ["bhd"],
		lang: ["ara"]
	},
	bi: {
		name: "Burundi",
		timezone: [],
		search: [
			"republic of burundi",
			"burundi",
			"uburundi",
			"bi",
			"republika y'uburundi",
			"république du burundi",
			"bdi"
		],
		call: ["257"],
		currency: ["bif"],
		lang: ["fra", "run"]
	},
	bj: {
		name: "Benin",
		timezone: [],
		search: ["republic of benin", "bénin", "bj", "république du bénin", "ben", "benin"],
		call: ["229"],
		currency: ["xof"],
		lang: ["fra"]
	},
	bl: {
		name: "Saint Barthélemy",
		timezone: [],
		search: [
			"collectivity of saint barthélemy",
			"saint-barthélemy",
			"bl",
			"st. barthelemy",
			"collectivité de saint-barthélemy",
			"blm",
			"saint barthélemy"
		],
		call: ["590"],
		currency: ["eur"],
		lang: ["fra"]
	},
	bm: {
		name: "Bermuda",
		timezone: [],
		search: ["bermuda", "bm", "the islands of bermuda", "the bermudas", "somers isles", "bmu"],
		call: ["1441"],
		currency: ["bmd"],
		lang: ["eng"]
	},
	bn: {
		name: "Brunei",
		timezone: ["+08:00"],
		search: [
			"nation of brunei, abode of peace",
			"negara brunei darussalam",
			"bn",
			"brunei darussalam",
			"nation of brunei",
			"the abode of peace",
			"brn",
			"brunei"
		],
		call: ["673"],
		currency: ["bnd"],
		lang: ["msa"]
	},
	bo: {
		name: "Bolivia",
		timezone: ["-04:00"],
		search: [
			"plurinational state of bolivia",
			"wuliwya",
			"volívia",
			"buliwya",
			"bolivia",
			"bo",
			"bolivia, plurinational state of",
			"estado plurinacional de bolivia",
			"buliwya mamallaqta",
			"wuliwya suyu",
			"tetã volívia",
			"bol"
		],
		call: ["591"],
		currency: ["bob"],
		lang: ["aym", "grn", "que", "spa"]
	},
	bq: {
		name: "Caribbean Netherlands",
		timezone: [],
		search: [
			"bonaire, sint eustatius and saba",
			"caribisch nederland",
			"boneiru, sint eustatius y saba",
			"bes islands",
			"bes",
			"caribbean netherlands"
		],
		call: ["599"],
		currency: ["usd"],
		lang: ["eng", "nld", "pap"]
	},
	br: {
		name: "Brazil",
		timezone: ["-02:00", "-03:00", "-04:00", "-05:00"],
		search: ["federative republic of brazil", "brasil", "br", "república federativa do brasil", "bra", "brazil"],
		call: ["55"],
		currency: ["brl"],
		lang: ["por"]
	},
	bs: {
		name: "Bahamas",
		timezone: [],
		search: ["commonwealth of the bahamas", "bahamas", "bs", "bhs"],
		call: ["1242"],
		currency: ["bsd"],
		lang: ["eng"]
	},
	bt: {
		name: "Bhutan",
		timezone: ["+06:00"],
		search: ["kingdom of bhutan", "འབྲུག་ཡུལ་", "bt", "btn", "bhutan"],
		call: ["975"],
		currency: ["btn", "inr"],
		lang: ["dzo"]
	},
	bv: {
		name: "Bouvet Island",
		timezone: [],
		search: ["bouvet island", "bouvetøya", "bv", "bouvet-øya", "bvt"],
		call: [],
		currency: ["nok"],
		lang: ["nor"]
	},
	bw: {
		name: "Botswana",
		timezone: ["+02:00"],
		search: ["republic of botswana", "botswana", "bw", "lefatshe la botswana", "bwa"],
		call: ["267"],
		currency: ["bwp"],
		lang: ["eng", "tsn"]
	},
	by: {
		name: "Belarus",
		timezone: ["+03:00"],
		search: [
			"republic of belarus",
			"белару́сь",
			"беларусь",
			"by",
			"bielaruś",
			"белоруссия",
			"республика белоруссия",
			"blr",
			"belarus"
		],
		call: ["375"],
		currency: ["byn"],
		lang: ["bel", "rus"]
	},
	ca: {
		name: "Canada",
		timezone: ["-03:30", "-04:00", "-05:00", "-06:00", "-07:00", "-08:00"],
		search: ["canada", "ca", "can"],
		call: ["1"],
		currency: ["cad"],
		lang: ["eng", "fra"]
	},
	cc: {
		name: "Cocos (Keeling) Islands",
		timezone: [],
		search: [
			"territory of the cocos (keeling) islands",
			"cocos (keeling) islands",
			"cc",
			"keeling islands",
			"cocos islands",
			"cck"
		],
		call: ["61"],
		currency: ["aud"],
		lang: ["eng"]
	},
	cd: {
		name: "DR Congo",
		timezone: ["+01:00", "+02:00"],
		search: [
			"democratic republic of the congo",
			"rd congo",
			"repubilika ya kongo demokratiki",
			"republiki ya kongó demokratiki",
			"ditunga dia kongu wa mungalaata",
			"jamhuri ya kidemokrasia ya kongo",
			"cd",
			"congo-kinshasa",
			"congo, the democratic republic of the",
			"drc",
			"cod",
			"dr congo"
		],
		call: ["243"],
		currency: ["cdf"],
		lang: ["fra", "kon", "lin", "lua", "swa"]
	},
	cf: {
		name: "Central African Republic",
		timezone: [],
		search: ["central african republic", "république centrafricaine", "bêafrîka", "cf", "caf"],
		call: ["236"],
		currency: ["xaf"],
		lang: ["fra", "sag"]
	},
	cg: {
		name: "Republic of the Congo",
		timezone: [],
		search: [
			"republic of the congo",
			"république du congo",
			"repubilika ya kongo",
			"republíki ya kongó",
			"cg",
			"congo",
			"congo-brazzaville",
			"cog"
		],
		call: ["242"],
		currency: ["xaf"],
		lang: ["fra", "kon", "lin"]
	},
	ch: {
		name: "Switzerland",
		timezone: ["+01:00"],
		search: ["swiss confederation", "suisse", "schweiz", "svizzera", "svizra", "ch", "che", "switzerland"],
		call: ["41"],
		currency: ["chf"],
		lang: ["fra", "gsw", "ita", "roh"]
	},
	ci: {
		name: "Ivory Coast",
		timezone: ["+00:00"],
		search: ["republic of côte d'ivoire", "côte d'ivoire", "ci", "république de côte d'ivoire", "civ", "ivory coast"],
		call: ["225"],
		currency: ["xof"],
		lang: ["fra"]
	},
	ck: {
		name: "Cook Islands",
		timezone: [],
		search: ["cook islands", "kūki 'āirani", "ck", "cok"],
		call: ["682"],
		currency: ["nzd", "ckd"],
		lang: ["eng", "rar"]
	},
	cl: {
		name: "Chile",
		timezone: ["-04:00", "-05:00"],
		search: ["republic of chile", "chile", "cl", "república de chile", "chl"],
		call: ["56"],
		currency: ["clp"],
		lang: ["spa"]
	},
	cm: {
		name: "Cameroon",
		timezone: ["+01:00"],
		search: ["republic of cameroon", "cameroon", "cameroun", "cm", "république du cameroun", "cmr"],
		call: ["237"],
		currency: ["xaf"],
		lang: ["eng", "fra"]
	},
	cn: {
		name: "China",
		timezone: ["+08:00", "+06:00"],
		search: [
			"people's republic of china",
			"中国",
			"cn",
			"zhōngguó",
			"zhongguo",
			"zhonghua",
			"中华人民共和国",
			"zhōnghuá rénmín gònghéguó",
			"chn",
			"china"
		],
		call: ["86"],
		currency: ["cny"],
		lang: ["zho"]
	},
	co: {
		name: "Colombia",
		timezone: ["-05:00"],
		search: ["republic of colombia", "colombia", "co", "república de colombia", "col"],
		call: ["57"],
		currency: ["cop"],
		lang: ["spa"]
	},
	cr: {
		name: "Costa Rica",
		timezone: ["-06:00"],
		search: ["republic of costa rica", "costa rica", "cr", "república de costa rica", "cri"],
		call: ["506"],
		currency: ["crc"],
		lang: ["spa"]
	},
	cu: {
		name: "Cuba",
		timezone: ["-05:00"],
		search: ["republic of cuba", "cuba", "cu", "república de cuba", "cub"],
		call: ["53"],
		currency: ["cuc", "cup"],
		lang: ["spa"]
	},
	cv: {
		name: "Cape Verde",
		timezone: [],
		search: ["republic of cabo verde", "cabo verde", "cv", "república de cabo verde", "cpv", "cape verde"],
		call: ["238"],
		currency: ["cve"],
		lang: ["por"]
	},
	cw: {
		name: "Curaçao",
		timezone: [],
		search: ["country of curaçao", "curaçao", "pais kòrsou", "cw", "curacao", "kòrsou", "land curaçao", "cuw"],
		call: ["5999"],
		currency: ["ang"],
		lang: ["eng", "nld", "pap"]
	},
	cx: {
		name: "Christmas Island",
		timezone: [],
		search: ["territory of christmas island", "christmas island", "cx", "cxr"],
		call: ["61"],
		currency: ["aud"],
		lang: ["eng"]
	},
	cy: {
		name: "Cyprus",
		timezone: [],
		search: [
			"republic of cyprus",
			"κύπρος",
			"kıbrıs",
			"cy",
			"kýpros",
			"κυπριακή δημοκρατία",
			"kıbrıs cumhuriyeti",
			"cyp",
			"cyprus"
		],
		call: ["357"],
		currency: ["eur"],
		lang: ["ell", "tur"]
	},
	cz: {
		name: "Czechia",
		timezone: ["+01:00"],
		search: ["czech republic", "česko", "cz", "česká republika", "cze", "czechia"],
		call: ["420"],
		currency: ["czk"],
		lang: ["ces", "slk"]
	},
	de: {
		name: "Germany",
		timezone: ["+01:00"],
		search: ["federal republic of germany", "deutschland", "de", "bundesrepublik deutschland", "deu", "germany"],
		call: ["49"],
		currency: ["eur"],
		lang: ["deu"]
	},
	dj: {
		name: "Djibouti",
		timezone: ["+03:00"],
		search: [
			"republic of djibouti",
			"جيبوتي‎",
			"djibouti",
			"dj",
			"jabuuti",
			"gabuuti",
			"république de djibouti",
			"gabuutih ummuuno",
			"jamhuuriyadda jabuuti",
			"dji"
		],
		call: ["253"],
		currency: ["djf"],
		lang: ["ara", "fra"]
	},
	dk: {
		name: "Denmark",
		timezone: ["+01:00"],
		search: ["kingdom of denmark", "danmark", "dk", "kongeriget danmark", "dnk", "denmark"],
		call: ["45"],
		currency: ["dkk"],
		lang: ["dan"]
	},
	dm: {
		name: "Dominica",
		timezone: [],
		search: ["commonwealth of dominica", "dominica", "dm", "dominique", "wai‘tu kubuli", "dma"],
		call: ["1767"],
		currency: ["xcd"],
		lang: ["eng"]
	},
	do: {
		name: "Dominican Republic",
		timezone: ["-04:00"],
		search: ["dominican republic", "república dominicana", "do", "dom"],
		call: ["1809", "1829", "1849"],
		currency: ["dop"],
		lang: ["spa"]
	},
	dz: {
		name: "Algeria",
		timezone: ["+01:00"],
		search: ["people's democratic republic of algeria", "الجزائر", "dz", "dzayer", "algérie", "dza", "algeria"],
		call: ["213"],
		currency: ["dzd"],
		lang: ["ara"]
	},
	ec: {
		name: "Ecuador",
		timezone: ["-05:00", "-06:00"],
		search: ["republic of ecuador", "ecuador", "ec", "república del ecuador", "ecu"],
		call: ["593"],
		currency: ["usd"],
		lang: ["spa"]
	},
	ee: {
		name: "Estonia",
		timezone: ["+02:00"],
		search: ["republic of estonia", "eesti", "ee", "eesti vabariik", "est", "estonia"],
		call: ["372"],
		currency: ["eur"],
		lang: ["est"]
	},
	eg: {
		name: "Egypt",
		timezone: ["+02:00"],
		search: ["arab republic of egypt", "مصر", "eg", "egy", "egypt"],
		call: ["20"],
		currency: ["egp"],
		lang: ["ara"]
	},
	eh: {
		name: "Western Sahara",
		timezone: [],
		search: [
			"sahrawi arab democratic republic",
			"western sahara",
			"الصحراء الغربية",
			"sahara occidental",
			"eh",
			"taneẓroft tutrimt",
			"esh"
		],
		call: ["212"],
		currency: ["mad", "dzd", "mro"],
		lang: ["ber", "mey", "spa"]
	},
	er: {
		name: "Eritrea",
		timezone: ["+03:00"],
		search: [
			"state of eritrea",
			"إرتريا‎",
			"eritrea",
			"ኤርትራ",
			"er",
			"ሃገረ ኤርትራ",
			"dawlat iritriyá",
			"ʾertrā",
			"iritriyā",
			"eri"
		],
		call: ["291"],
		currency: ["ern"],
		lang: ["ara", "eng", "tir"]
	},
	es: {
		name: "Spain",
		timezone: ["+01:00", "+00:00"],
		search: ["kingdom of spain", "españa", "es", "reino de españa", "esp", "spain"],
		call: ["34"],
		currency: ["eur"],
		lang: ["spa"]
	},
	et: {
		name: "Ethiopia",
		timezone: ["+03:00"],
		search: [
			"federal democratic republic of ethiopia",
			"ኢትዮጵያ",
			"et",
			"ʾītyōṗṗyā",
			"የኢትዮጵያ ፌዴራላዊ ዲሞክራሲያዊ ሪፐብሊክ",
			"eth",
			"ethiopia"
		],
		call: ["251"],
		currency: ["etb"],
		lang: ["amh"]
	},
	fi: {
		name: "Finland",
		timezone: ["+02:00"],
		search: ["republic of finland", "suomi", "finland", "fi", "suomen tasavalta", "republiken finland", "fin"],
		call: ["358"],
		currency: ["eur"],
		lang: ["fin", "swe"]
	},
	fj: {
		name: "Fiji",
		timezone: [],
		search: ["republic of fiji", "fiji", "viti", "फिजी", "fj", "matanitu ko viti", "fijī gaṇarājya", "fji"],
		call: ["679"],
		currency: ["fjd"],
		lang: ["eng", "fij", "hif"]
	},
	fm: {
		name: "Micronesia",
		timezone: [],
		search: ["federated states of micronesia", "micronesia", "fm", "micronesia, federated states of", "fsm"],
		call: ["691"],
		currency: ["usd"],
		lang: ["eng"]
	},
	fo: {
		name: "Faroe Islands",
		timezone: ["+00:00"],
		search: ["faroe islands", "færøerne", "føroyar", "fo", "fro"],
		call: ["298"],
		currency: ["dkk"],
		lang: ["dan", "fao"]
	},
	fr: {
		name: "France",
		timezone: ["+01:00"],
		search: ["french republic", "france", "fr", "république française", "fra"],
		call: ["33"],
		currency: ["eur"],
		lang: ["fra"]
	},
	ga: {
		name: "Gabon",
		timezone: [],
		search: ["gabonese republic", "gabon", "ga", "république gabonaise", "gab"],
		call: ["241"],
		currency: ["xaf"],
		lang: ["fra"]
	},
	gb: {
		name: "United Kingdom",
		timezone: ["+00:00"],
		search: [
			"united kingdom of great britain and northern ireland",
			"united kingdom",
			"gb",
			"uk",
			"great britain",
			"gbr",
			"england"
		],
		call: ["44"],
		currency: ["gbp"],
		lang: ["eng"]
	},
	gd: {
		name: "Grenada",
		timezone: [],
		search: ["grenada", "gd", "grd"],
		call: ["1473"],
		currency: ["xcd"],
		lang: ["eng"]
	},
	ge: {
		name: "Georgia",
		timezone: ["+04:00"],
		search: ["georgia", "საქართველო", "ge", "sakartvelo", "geo"],
		call: ["995"],
		currency: ["gel"],
		lang: ["kat"]
	},
	gf: {
		name: "French Guiana",
		timezone: [],
		search: ["guiana", "guyane française", "gf", "guyane", "guf", "french guiana"],
		call: ["594"],
		currency: ["eur"],
		lang: ["fra"]
	},
	gg: {
		name: "Guernsey",
		timezone: [],
		search: ["bailiwick of guernsey", "guernsey", "guernesey", "dgèrnésiais", "gg", "bailliage de guernesey", "ggy"],
		call: ["44"],
		currency: ["gbp"],
		lang: ["eng", "fra", "nfr"]
	},
	gh: {
		name: "Ghana",
		timezone: [],
		search: ["republic of ghana", "ghana", "gh", "gha"],
		call: ["233"],
		currency: ["ghs"],
		lang: ["eng"]
	},
	gi: {
		name: "Gibraltar",
		timezone: [],
		search: ["gibraltar", "gi", "gib"],
		call: ["350"],
		currency: ["gip"],
		lang: ["eng"]
	},
	gl: {
		name: "Greenland",
		timezone: ["-03:00", "-01:00", "-04:00"],
		search: ["greenland", "kalaallit nunaat", "gl", "grønland", "grl"],
		call: ["299"],
		currency: ["dkk"],
		lang: ["kal"]
	},
	gm: {
		name: "Gambia",
		timezone: [],
		search: ["republic of the gambia", "gambia", "gm", "gmb"],
		call: ["220"],
		currency: ["gmd"],
		lang: ["eng"]
	},
	gn: {
		name: "Guinea",
		timezone: [],
		search: ["republic of guinea", "guinée", "gn", "république de guinée", "gin", "guinea"],
		call: ["224"],
		currency: ["gnf"],
		lang: ["fra"]
	},
	gp: {
		name: "Guadeloupe",
		timezone: [],
		search: ["guadeloupe", "gp", "gwadloup", "glp"],
		call: ["590"],
		currency: ["eur"],
		lang: ["fra"]
	},
	gq: {
		name: "Equatorial Guinea",
		timezone: [],
		search: [
			"republic of equatorial guinea",
			"guinée équatoriale",
			"guiné equatorial",
			"guinea ecuatorial",
			"gq",
			"república de guinea ecuatorial",
			"république de guinée équatoriale",
			"república da guiné equatorial",
			"gnq",
			"equatorial guinea"
		],
		call: ["240"],
		currency: ["xaf"],
		lang: ["fra", "por", "spa"]
	},
	gr: {
		name: "Greece",
		timezone: ["+02:00"],
		search: ["hellenic republic", "ελλάδα", "gr", "elláda", "ελληνική δημοκρατία", "grc", "greece"],
		call: ["30"],
		currency: ["eur"],
		lang: ["ell"]
	},
	gu: {
		name: "Guam",
		timezone: [],
		search: ["guam", "guåhån", "gu", "gum"],
		call: ["1671"],
		currency: ["usd"],
		lang: ["cha", "eng", "spa"]
	},
	gw: {
		name: "Guinea-Bissau",
		timezone: [],
		search: ["republic of guinea-bissau", "guiné-bissau", "gw", "república da guiné-bissau", "gnb", "guinea-bissau"],
		call: ["245"],
		currency: ["xof"],
		lang: ["por", "pov"]
	},
	gy: {
		name: "Guyana",
		timezone: [],
		search: ["co-operative republic of guyana", "guyana", "gy", "guy"],
		call: ["592"],
		currency: ["gyd"],
		lang: ["eng"]
	},
	hk: {
		name: "Hong Kong",
		timezone: ["+08:00"],
		search: [
			"hong kong special administrative region of the people's republic of china",
			"hong kong",
			"香港",
			"hk",
			"hkg"
		],
		call: ["852"],
		currency: ["hkd"],
		lang: ["eng", "zho"]
	},
	hm: {
		name: "Heard Island and McDonald Islands",
		timezone: [],
		search: ["heard island and mcdonald islands", "hm", "hmd"],
		call: [],
		currency: ["aud"],
		lang: ["eng"]
	},
	hn: {
		name: "Honduras",
		timezone: ["-06:00"],
		search: ["republic of honduras", "honduras", "hn", "república de honduras", "hnd"],
		call: ["504"],
		currency: ["hnl"],
		lang: ["spa"]
	},
	hr: {
		name: "Croatia",
		timezone: ["+01:00"],
		search: ["republic of croatia", "hrvatska", "hr", "republika hrvatska", "hrv", "croatia"],
		call: ["385"],
		currency: ["hrk"],
		lang: ["hrv"]
	},
	ht: {
		name: "Haiti",
		timezone: ["-05:00"],
		search: ["republic of haiti", "haïti", "ayiti", "ht", "république d'haïti", "repiblik ayiti", "hti", "haiti"],
		call: ["509"],
		currency: ["htg", "usd"],
		lang: ["fra", "hat"]
	},
	hu: {
		name: "Hungary",
		timezone: ["+01:00"],
		search: ["hungary", "magyarország", "hu", "hun"],
		call: ["36"],
		currency: ["huf"],
		lang: ["hun"]
	},
	id: {
		name: "Indonesia",
		timezone: ["+07:00", "+08:00", "+09:00"],
		search: ["republic of indonesia", "indonesia", "id", "republik indonesia", "idn"],
		call: ["62"],
		currency: ["idr"],
		lang: ["ind"]
	},
	ie: {
		name: "Ireland",
		timezone: ["+00:00"],
		search: ["republic of ireland", "ireland", "éire", "ie", "poblacht na héireann", "irl"],
		call: ["353"],
		currency: ["eur"],
		lang: ["eng", "gle"]
	},
	il: {
		name: "Israel",
		timezone: ["+02:00"],
		search: ["state of israel", "إسرائيل", "ישראל", "il", "medīnat yisrā'el", "isr", "israel"],
		call: ["972"],
		currency: ["ils"],
		lang: ["ara", "heb"]
	},
	im: {
		name: "Isle of Man",
		timezone: [],
		search: ["isle of man", "mannin", "im", "ellan vannin", "mann", "imn"],
		call: ["44"],
		currency: ["gbp"],
		lang: ["eng", "glv"]
	},
	in: {
		name: "India",
		timezone: ["+05:30"],
		search: ["republic of india", "india", "भारत", "இந்தியா", "in", "bhārat", "bharat ganrajya", "ind"],
		call: ["91"],
		currency: ["inr"],
		lang: ["eng", "hin", "tam"]
	},
	io: {
		name: "British Indian Ocean Territory",
		timezone: [],
		search: ["british indian ocean territory", "io", "iot"],
		call: ["246"],
		currency: ["usd"],
		lang: ["eng"]
	},
	iq: {
		name: "Iraq",
		timezone: ["+03:00"],
		search: ["republic of iraq", "العراق", "ܩܘܼܛܢܵܐ", "کۆماری", "iq", "jumhūriyyat al-‘irāq", "irq", "iraq"],
		call: ["964"],
		currency: ["iqd"],
		lang: ["ara", "arc", "ckb"]
	},
	ir: {
		name: "Iran",
		timezone: ["+03:30"],
		search: [
			"islamic republic of iran",
			"ایران",
			"ir",
			"iran, islamic republic of",
			"jomhuri-ye eslāmi-ye irān",
			"irn",
			"iran"
		],
		call: ["98"],
		currency: ["irr"],
		lang: ["fas"]
	},
	is: {
		name: "Iceland",
		timezone: ["+00:00"],
		search: ["iceland", "ísland", "is", "island", "republic of iceland", "lýðveldið ísland", "isl"],
		call: ["354"],
		currency: ["isk"],
		lang: ["isl"]
	},
	it: {
		name: "Italy",
		timezone: ["+01:00"],
		search: ["italian republic", "italia", "it", "repubblica italiana", "ita", "italy"],
		call: ["39"],
		currency: ["eur"],
		lang: ["ita"]
	},
	je: {
		name: "Jersey",
		timezone: [],
		search: ["bailiwick of jersey", "jersey", "jèrri", "je", "bailliage de jersey", "bailliage dé jèrri", "jey"],
		call: ["44"],
		currency: ["gbp"],
		lang: ["eng", "fra", "nrf"]
	},
	jm: {
		name: "Jamaica",
		timezone: ["-05:00"],
		search: ["jamaica", "jm", "jam"],
		call: ["1876"],
		currency: ["jmd"],
		lang: ["eng", "jam"]
	},
	jo: {
		name: "Jordan",
		timezone: ["+02:00"],
		search: ["hashemite kingdom of jordan", "الأردن", "jo", "al-mamlakah al-urdunīyah al-hāshimīyah", "jor", "jordan"],
		call: ["962"],
		currency: ["jod"],
		lang: ["ara"]
	},
	jp: {
		name: "Japan",
		timezone: ["+09:00"],
		search: ["japan", "日本", "jp", "nippon", "nihon", "jpn"],
		call: ["81"],
		currency: ["jpy"],
		lang: ["jpn"]
	},
	ke: {
		name: "Kenya",
		timezone: ["+03:00"],
		search: ["republic of kenya", "kenya", "ke", "jamhuri ya kenya", "ken"],
		call: ["254"],
		currency: ["kes"],
		lang: ["eng", "swa"]
	},
	kg: {
		name: "Kyrgyzstan",
		timezone: ["+06:00"],
		search: [
			"kyrgyz republic",
			"кыргызстан",
			"киргизия",
			"kg",
			"кыргыз республикасы",
			"kyrgyz respublikasy",
			"kgz",
			"kyrgyzstan"
		],
		call: ["996"],
		currency: ["kgs"],
		lang: ["kir", "rus"]
	},
	kh: {
		name: "Cambodia",
		timezone: ["+07:00"],
		search: ["kingdom of cambodia", "kâmpŭchéa", "kh", "khm", "cambodia"],
		call: ["855"],
		currency: ["khr"],
		lang: ["khm"]
	},
	ki: {
		name: "Kiribati",
		timezone: [],
		search: [
			"independent and sovereign republic of kiribati",
			"kiribati",
			"ki",
			"republic of kiribati",
			"ribaberiki kiribati",
			"kir"
		],
		call: ["686"],
		currency: ["aud"],
		lang: ["eng", "gil"]
	},
	km: {
		name: "Comoros",
		timezone: [],
		search: [
			"union of the comoros",
			"القمر‎",
			"comores",
			"komori",
			"km",
			"union des comores",
			"udzima wa komori",
			"al-ittiḥād al-qumurī",
			"com",
			"comoros"
		],
		call: ["269"],
		currency: ["kmf"],
		lang: ["ara", "fra", "zdj"]
	},
	kn: {
		name: "Saint Kitts and Nevis",
		timezone: [],
		search: [
			"federation of saint christopher and nevisa",
			"saint kitts and nevis",
			"kn",
			"federation of saint christopher and nevis",
			"kna"
		],
		call: ["1869"],
		currency: ["xcd"],
		lang: ["eng"]
	},
	kp: {
		name: "North Korea",
		timezone: [],
		search: [
			"democratic people's republic of korea",
			"조선",
			"kp",
			"조선민주주의인민공화국",
			"chosŏn minjujuŭi inmin konghwaguk",
			"korea, democratic people's republic of",
			"북한",
			"북조선",
			"prk",
			"north korea"
		],
		call: ["850"],
		currency: ["kpw"],
		lang: ["kor"]
	},
	kr: {
		name: "South Korea",
		timezone: ["+09:00"],
		search: ["republic of korea", "한국", "kr", "korea, republic of", "남한", "남조선", "kor", "south korea"],
		call: ["82"],
		currency: ["krw"],
		lang: ["kor"]
	},
	kw: {
		name: "Kuwait",
		timezone: ["+03:00"],
		search: ["state of kuwait", "الكويت", "kw", "dawlat al-kuwait", "kwt", "kuwait"],
		call: ["965"],
		currency: ["kwd"],
		lang: ["ara"]
	},
	ky: {
		name: "Cayman Islands",
		timezone: [],
		search: ["cayman islands", "ky", "cym"],
		call: ["1345"],
		currency: ["kyd"],
		lang: ["eng"]
	},
	kz: {
		name: "Kazakhstan",
		timezone: ["+06:00", "+05:00"],
		search: [
			"republic of kazakhstan",
			"қазақстан",
			"казахстан",
			"kz",
			"qazaqstan",
			"қазақстан республикасы",
			"qazaqstan respublïkası",
			"республика казахстан",
			"respublika kazakhstan",
			"kaz",
			"kazakhstan"
		],
		call: ["7"],
		currency: ["kzt"],
		lang: ["kaz", "rus"]
	},
	la: {
		name: "Laos",
		timezone: ["+07:00"],
		search: [
			"lao people's democratic republic",
			"ສປປລາວ",
			"la",
			"lao",
			"sathalanalat paxathipatai paxaxon lao",
			"laos"
		],
		call: ["856"],
		currency: ["lak"],
		lang: ["lao"]
	},
	lb: {
		name: "Lebanon",
		timezone: ["+02:00"],
		search: ["lebanese republic", "لبنان", "liban", "lb", "al-jumhūrīyah al-libnānīyah", "lbn", "lebanon"],
		call: ["961"],
		currency: ["lbp"],
		lang: ["ara", "fra"]
	},
	lc: {
		name: "Saint Lucia",
		timezone: [],
		search: ["saint lucia", "lc", "lca"],
		call: ["1758"],
		currency: ["xcd"],
		lang: ["eng"]
	},
	li: {
		name: "Liechtenstein",
		timezone: ["+01:00"],
		search: ["principality of liechtenstein", "liechtenstein", "li", "fürstentum liechtenstein", "lie"],
		call: ["423"],
		currency: ["chf"],
		lang: ["deu"]
	},
	lk: {
		name: "Sri Lanka",
		timezone: ["+05:30"],
		search: [
			"democratic socialist republic of sri lanka",
			"ශ්‍රී ලංකාව",
			"இலங்கை",
			"lk",
			"ilaṅkai",
			"lka",
			"sri lanka"
		],
		call: ["94"],
		currency: ["lkr"],
		lang: ["sin", "tam"]
	},
	lr: {
		name: "Liberia",
		timezone: [],
		search: ["republic of liberia", "liberia", "lr", "lbr"],
		call: ["231"],
		currency: ["lrd"],
		lang: ["eng"]
	},
	ls: {
		name: "Lesotho",
		timezone: [],
		search: ["kingdom of lesotho", "lesotho", "ls", "muso oa lesotho", "lso"],
		call: ["266"],
		currency: ["lsl", "zar"],
		lang: ["eng", "sot"]
	},
	lt: {
		name: "Lithuania",
		timezone: ["+02:00"],
		search: ["republic of lithuania", "lietuva", "lt", "lietuvos respublika", "ltu", "lithuania"],
		call: ["370"],
		currency: ["eur"],
		lang: ["lit"]
	},
	lu: {
		name: "Luxembourg",
		timezone: ["+01:00"],
		search: [
			"grand duchy of luxembourg",
			"luxemburg",
			"luxembourg",
			"lëtzebuerg",
			"lu",
			"grand-duché de luxembourg",
			"großherzogtum luxemburg",
			"groussherzogtum lëtzebuerg",
			"lux"
		],
		call: ["352"],
		currency: ["eur"],
		lang: ["deu", "fra", "ltz"]
	},
	lv: {
		name: "Latvia",
		timezone: ["+02:00"],
		search: ["republic of latvia", "latvija", "lv", "latvijas republika", "lva", "latvia"],
		call: ["371"],
		currency: ["eur"],
		lang: ["lav"]
	},
	ly: {
		name: "Libya",
		timezone: ["+02:00"],
		search: ["state of libya", "‏ليبيا", "ly", "dawlat libya", "lby", "libya"],
		call: ["218"],
		currency: ["lyd"],
		lang: ["ara"]
	},
	ma: {
		name: "Morocco",
		timezone: ["+00:00"],
		search: ["kingdom of morocco", "المغرب", "ⵍⵎⴰⵖⵔⵉⴱ", "ma", "al-mamlakah al-maġribiyah", "mar", "morocco"],
		call: ["212"],
		currency: ["mad"],
		lang: ["ara", "ber"]
	},
	mc: {
		name: "Monaco",
		timezone: ["+01:00"],
		search: ["principality of monaco", "monaco", "mc", "principauté de monaco", "mco"],
		call: ["377"],
		currency: ["eur"],
		lang: ["fra"]
	},
	md: {
		name: "Moldova",
		timezone: ["+02:00"],
		search: ["republic of moldova", "moldova", "md", "moldova, republic of", "republica moldova", "mda"],
		call: ["373"],
		currency: ["mdl"],
		lang: ["ron"]
	},
	me: {
		name: "Montenegro",
		timezone: ["+01:00"],
		search: ["montenegro", "црна гора", "me", "crna gora", "mne"],
		call: ["382"],
		currency: ["eur"],
		lang: ["srp"]
	},
	mf: {
		name: "Saint Martin",
		timezone: [],
		search: [
			"saint martin",
			"saint-martin",
			"mf",
			"collectivity of saint martin",
			"collectivité de saint-martin",
			"saint martin (french part)",
			"maf"
		],
		call: ["590"],
		currency: ["eur"],
		lang: ["fra"]
	},
	mg: {
		name: "Madagascar",
		timezone: [],
		search: [
			"republic of madagascar",
			"madagascar",
			"madagasikara",
			"mg",
			"repoblikan'i madagasikara",
			"république de madagascar",
			"mdg"
		],
		call: ["261"],
		currency: ["mga"],
		lang: ["fra", "mlg"]
	},
	mh: {
		name: "Marshall Islands",
		timezone: [],
		search: ["republic of the marshall islands", "marshall islands", "m̧ajeļ", "mh", "aolepān aorōkin m̧ajeļ", "mhl"],
		call: ["692"],
		currency: ["usd"],
		lang: ["eng", "mah"]
	},
	mk: {
		name: "Macedonia",
		timezone: ["+01:00"],
		search: [
			"republic of macedonia",
			"македонија",
			"mk",
			"macedonia, the former yugoslav republic of",
			"република македонија",
			"mkd",
			"macedonia"
		],
		call: ["389"],
		currency: ["mkd"],
		lang: ["mkd"]
	},
	ml: {
		name: "Mali",
		timezone: ["+00:00"],
		search: ["republic of mali", "mali", "ml", "république du mali", "mli"],
		call: ["223"],
		currency: ["xof"],
		lang: ["fra"]
	},
	mm: {
		name: "Myanmar",
		timezone: ["+06:30"],
		search: [
			"republic of the union of myanmar",
			"မြန်မာ",
			"mm",
			"burma",
			"pyidaunzu thanmăda myăma nainngandaw",
			"mmr",
			"myanmar"
		],
		call: ["95"],
		currency: ["mmk"],
		lang: ["mya"]
	},
	mn: {
		name: "Mongolia",
		timezone: ["+08:00"],
		search: ["mongolia", "монгол улс", "mn", "mng"],
		call: ["976"],
		currency: ["mnt"],
		lang: ["mon"]
	},
	mo: {
		name: "Macau",
		timezone: ["+08:00"],
		search: [
			"macao special administrative region of the people's republic of china",
			"macau",
			"澳门",
			"mo",
			"macao",
			"中華人民共和國澳門特別行政區",
			"região administrativa especial de macau da república popular da china",
			"mac"
		],
		call: ["853"],
		currency: ["mop"],
		lang: ["por", "zho"]
	},
	mp: {
		name: "Northern Mariana Islands",
		timezone: [],
		search: [
			"commonwealth of the northern mariana islands",
			"northern mariana islands",
			"na islas mariånas",
			"mp",
			"sankattan siha na islas mariånas",
			"mnp"
		],
		call: ["1670"],
		currency: ["usd"],
		lang: ["cal", "cha", "eng"]
	},
	mq: {
		name: "Martinique",
		timezone: [],
		search: ["martinique", "mq", "mtq"],
		call: ["596"],
		currency: ["eur"],
		lang: ["fra"]
	},
	mr: {
		name: "Mauritania",
		timezone: [],
		search: [
			"islamic republic of mauritania",
			"موريتانيا",
			"mr",
			"al-jumhūriyyah al-ʾislāmiyyah al-mūrītāniyyah",
			"mrt",
			"mauritania"
		],
		call: ["222"],
		currency: ["mro"],
		lang: ["ara"]
	},
	ms: {
		name: "Montserrat",
		timezone: [],
		search: ["montserrat", "ms", "msr"],
		call: ["1664"],
		currency: ["xcd"],
		lang: ["eng"]
	},
	mt: {
		name: "Malta",
		timezone: ["+01:00"],
		search: ["republic of malta", "malta", "mt", "repubblika ta' malta", "mlt"],
		call: ["356"],
		currency: ["eur"],
		lang: ["eng", "mlt"]
	},
	mu: {
		name: "Mauritius",
		timezone: [],
		search: ["republic of mauritius", "mauritius", "maurice", "moris", "mu", "république de maurice", "mus"],
		call: ["230"],
		currency: ["mur"],
		lang: ["eng", "fra", "mfe"]
	},
	mv: {
		name: "Maldives",
		timezone: ["+05:00"],
		search: [
			"republic of the maldives",
			"ދިވެހިރާއްޖޭގެ",
			"mv",
			"maldive islands",
			"dhivehi raajjeyge jumhooriyya",
			"mdv",
			"maldives"
		],
		call: ["960"],
		currency: ["mvr"],
		lang: ["div"]
	},
	mw: {
		name: "Malawi",
		timezone: [],
		search: ["republic of malawi", "malawi", "malaŵi", "mw", "mwi"],
		call: ["265"],
		currency: ["mwk"],
		lang: ["eng", "nya"]
	},
	my: {
		name: "Malaysia",
		timezone: ["+08:00"],
		search: ["malaysia", "مليسيا", "my", "mys"],
		call: ["60"],
		currency: ["myr"],
		lang: ["eng", "msa"]
	},
	mz: {
		name: "Mozambique",
		timezone: [],
		search: ["republic of mozambique", "moçambique", "mz", "república de moçambique", "moz", "mozambique"],
		call: ["258"],
		currency: ["mzn"],
		lang: ["por"]
	},
	na: {
		name: "Namibia",
		timezone: [],
		search: ["republic of namibia", "namibië", "namibia", "na", "nam"],
		call: ["264"],
		currency: ["nad", "zar"],
		lang: ["afr", "deu", "eng", "her", "hgm", "kwn", "loz", "ndo", "tsn"]
	},
	nc: {
		name: "New Caledonia",
		timezone: [],
		search: ["new caledonia", "nouvelle-calédonie", "nc", "ncl"],
		call: ["687"],
		currency: ["xpf"],
		lang: ["fra"]
	},
	ne: {
		name: "Niger",
		timezone: [],
		search: ["republic of niger", "niger", "ne", "nijar", "ner"],
		call: ["227"],
		currency: ["xof"],
		lang: ["fra"]
	},
	nf: {
		name: "Norfolk Island",
		timezone: [],
		search: ["territory of norfolk island", "norfolk island", "norf'k ailen", "nf", "teratri of norf'k ailen", "nfk"],
		call: ["672"],
		currency: ["aud"],
		lang: ["eng", "pih"]
	},
	ng: {
		name: "Nigeria",
		timezone: ["+01:00"],
		search: ["federal republic of nigeria", "nigeria", "ng", "nijeriya", "naíjíríà", "nga"],
		call: ["234"],
		currency: ["ngn"],
		lang: ["eng"]
	},
	nl: {
		name: "Netherlands",
		timezone: ["+01:00"],
		search: ["kingdom of the netherlands", "nederland", "nl", "holland", "the netherlands", "nld", "netherlands"],
		call: ["31"],
		currency: ["eur"],
		lang: ["nld"]
	},
	no: {
		name: "Norway",
		timezone: ["+01:00"],
		search: [
			"kingdom of norway",
			"noreg",
			"norge",
			"norgga",
			"no",
			"kongeriket norge",
			"kongeriket noreg",
			"nor",
			"norway"
		],
		call: ["47"],
		currency: ["nok"],
		lang: ["nno", "nob", "smi"]
	},
	np: {
		name: "Nepal",
		timezone: ["+05:45"],
		search: ["federal democratic republic of nepal", "नेपाल", "np", "loktāntrik ganatantra nepāl", "npl", "nepal"],
		call: ["977"],
		currency: ["npr"],
		lang: ["nep"]
	},
	nr: {
		name: "Nauru",
		timezone: [],
		search: ["republic of nauru", "nauru", "nr", "naoero", "pleasant island", "ripublik naoero", "nru"],
		call: ["674"],
		currency: ["aud"],
		lang: ["eng", "nau"]
	},
	nu: {
		name: "Niue",
		timezone: [],
		search: ["niue", "niuē", "nu", "niu"],
		call: ["683"],
		currency: ["nzd"],
		lang: ["eng", "niu"]
	},
	nz: {
		name: "New Zealand",
		timezone: ["+12:00"],
		search: ["new zealand", "aotearoa", "nz", "nzl"],
		call: ["64"],
		currency: ["nzd"],
		lang: ["eng", "mri", "nzs"]
	},
	om: {
		name: "Oman",
		timezone: ["+04:00"],
		search: ["sultanate of oman", "عمان", "om", "salṭanat ʻumān", "omn", "oman"],
		call: ["968"],
		currency: ["omr"],
		lang: ["ara"]
	},
	pa: {
		name: "Panama",
		timezone: ["-05:00"],
		search: ["republic of panama", "panamá", "pa", "república de panamá", "pan", "panama"],
		call: ["507"],
		currency: ["pab", "usd"],
		lang: ["spa"]
	},
	pe: {
		name: "Peru",
		timezone: ["-05:00"],
		search: ["republic of peru", "piruw", "perú", "pe", "república del perú", "per", "peru"],
		call: ["51"],
		currency: ["pen"],
		lang: ["aym", "que", "spa"]
	},
	pf: {
		name: "French Polynesia",
		timezone: [],
		search: ["french polynesia", "polynésie française", "pf", "pōrīnetia farāni", "pyf"],
		call: ["689"],
		currency: ["xpf"],
		lang: ["fra"]
	},
	pg: {
		name: "Papua New Guinea",
		timezone: [],
		search: [
			"independent state of papua new guinea",
			"papua new guinea",
			"papua niu gini",
			"papua niugini",
			"pg",
			"independen stet bilong papua niugini",
			"png"
		],
		call: ["675"],
		currency: ["pgk"],
		lang: ["eng", "hmo", "tpi"]
	},
	ph: {
		name: "Philippines",
		timezone: ["+08:00"],
		search: ["republic of the philippines", "philippines", "pilipinas", "ph", "repúblika ng pilipinas", "phl"],
		call: ["63"],
		currency: ["php"],
		lang: ["eng", "fil"]
	},
	pk: {
		name: "Pakistan",
		timezone: ["+05:00"],
		search: [
			"islamic republic of pakistan",
			"pakistan",
			"پاكستان",
			"pk",
			"pākistān",
			"islāmī jumhūriya'eh pākistān",
			"pak"
		],
		call: ["92"],
		currency: ["pkr"],
		lang: ["eng", "urd"]
	},
	pl: {
		name: "Poland",
		timezone: ["+01:00"],
		search: ["republic of poland", "polska", "pl", "rzeczpospolita polska", "pol", "poland"],
		call: ["48"],
		currency: ["pln"],
		lang: ["pol"]
	},
	pm: {
		name: "Saint Pierre and Miquelon",
		timezone: [],
		search: [
			"saint pierre and miquelon",
			"saint-pierre-et-miquelon",
			"pm",
			"collectivité territoriale de saint-pierre-et-miquelon",
			"spm"
		],
		call: ["508"],
		currency: ["eur"],
		lang: ["fra"]
	},
	pn: {
		name: "Pitcairn Islands",
		timezone: [],
		search: [
			"pitcairn group of islands",
			"pitcairn islands",
			"pn",
			"pitcairn",
			"pitcairn henderson ducie and oeno islands",
			"pcn"
		],
		call: ["64"],
		currency: ["nzd"],
		lang: ["eng"]
	},
	pr: {
		name: "Puerto Rico",
		timezone: ["-04:00"],
		search: ["commonwealth of puerto rico", "puerto rico", "pr", "estado libre asociado de puerto rico", "pri"],
		call: ["1787", "1939"],
		currency: ["usd"],
		lang: ["eng", "spa"]
	},
	ps: {
		name: "Palestine",
		timezone: [],
		search: ["state of palestine", "فلسطين", "ps", "palestine, state of", "dawlat filasṭin", "pse", "palestine"],
		call: ["970"],
		currency: ["ils"],
		lang: ["ara"]
	},
	pt: {
		name: "Portugal",
		timezone: ["+00:00", "-01:00"],
		search: ["portuguese republic", "portugal", "pt", "portuguesa", "república portuguesa", "prt"],
		call: ["351"],
		currency: ["eur"],
		lang: ["por"]
	},
	pw: {
		name: "Palau",
		timezone: [],
		search: ["republic of palau", "palau", "belau", "pw", "beluu er a belau", "plw"],
		call: ["680"],
		currency: ["usd"],
		lang: ["eng", "pau"]
	},
	py: {
		name: "Paraguay",
		timezone: ["-04:00"],
		search: ["republic of paraguay", "paraguái", "paraguay", "py", "república del paraguay", "tetã paraguái", "pry"],
		call: ["595"],
		currency: ["pyg"],
		lang: ["grn", "spa"]
	},
	qa: {
		name: "Qatar",
		timezone: ["+03:00"],
		search: ["state of qatar", "قطر", "qa", "dawlat qaṭar", "qat", "qatar"],
		call: ["974"],
		currency: ["qar"],
		lang: ["ara"]
	},
	re: {
		name: "Réunion",
		timezone: ["+04:00"],
		search: ["réunion island", "la réunion", "re", "reunion", "reu", "réunion"],
		call: ["262"],
		currency: ["eur"],
		lang: ["fra"]
	},
	ro: {
		name: "Romania",
		timezone: ["+02:00"],
		search: ["romania", "românia", "ro", "rumania", "roumania", "rou"],
		call: ["40"],
		currency: ["ron"],
		lang: ["ron"]
	},
	rs: {
		name: "Serbia",
		timezone: ["+01:00"],
		search: ["republic of serbia", "србија", "rs", "srbija", "република србија", "republika srbija", "srb", "serbia"],
		call: ["381"],
		currency: ["rsd"],
		lang: ["srp"]
	},
	ru: {
		name: "Russia",
		timezone: ["+02:00", "+03:00", "+04:00", "+05:00", "+07:00", "+08:00", "+09:00", "+10:00", "+11:00", "+12:00"],
		search: ["russian federation", "россия", "ru", "российская федерация", "rus", "russia"],
		call: ["7"],
		currency: ["rub"],
		lang: ["rus"]
	},
	rw: {
		name: "Rwanda",
		timezone: ["+02:00"],
		search: ["republic of rwanda", "rwanda", "rw", "repubulika y'u rwanda", "république du rwanda", "rwa"],
		call: ["250"],
		currency: ["rwf"],
		lang: ["eng", "fra", "kin"]
	},
	sa: {
		name: "Saudi Arabia",
		timezone: ["+03:00"],
		search: [
			"kingdom of saudi arabia",
			"العربية السعودية",
			"saudi",
			"sa",
			"al-mamlakah al-‘arabiyyah as-su‘ūdiyyah",
			"sau",
			"saudi arabia"
		],
		call: ["966"],
		currency: ["sar"],
		lang: ["ara"]
	},
	sb: {
		name: "Solomon Islands",
		timezone: [],
		search: ["solomon islands", "sb", "slb"],
		call: ["677"],
		currency: ["sbd"],
		lang: ["eng"]
	},
	sc: {
		name: "Seychelles",
		timezone: [],
		search: [
			"republic of seychelles",
			"sesel",
			"seychelles",
			"sc",
			"repiblik sesel",
			"république des seychelles",
			"syc"
		],
		call: ["248"],
		currency: ["scr"],
		lang: ["crs", "eng", "fra"]
	},
	sd: {
		name: "Sudan",
		timezone: [],
		search: ["republic of the sudan", "السودان", "sudan", "sd", "jumhūrīyat as-sūdān", "sdn"],
		call: ["249"],
		currency: ["sdg"],
		lang: ["ara", "eng"]
	},
	se: {
		name: "Sweden",
		timezone: ["+01:00"],
		search: ["kingdom of sweden", "sverige", "se", "konungariket sverige", "swe", "sweden"],
		call: ["46"],
		currency: ["sek"],
		lang: ["swe"]
	},
	sg: {
		name: "Singapore",
		timezone: ["+08:00"],
		search: [
			"republic of singapore",
			"新加坡",
			"singapore",
			"singapura",
			"சிங்கப்பூர்",
			"sg",
			"republik singapura",
			"新加坡共和国",
			"sgp"
		],
		call: ["65"],
		currency: ["sgd"],
		lang: ["zho", "eng", "msa", "tam"]
	},
	sh: {
		name: "Saint Helena, Ascension and Tristan da Cunha",
		timezone: [],
		search: [
			"saint helena, ascension and tristan da cunha",
			"saint helena",
			"st. helena, ascension and tristan da cunha",
			"shn"
		],
		call: ["290", "247"],
		currency: ["shp", "gbp"],
		lang: ["eng"]
	},
	si: {
		name: "Slovenia",
		timezone: ["+01:00"],
		search: ["republic of slovenia", "slovenija", "si", "republika slovenija", "svn", "slovenia"],
		call: ["386"],
		currency: ["eur"],
		lang: ["slv"]
	},
	sj: {
		name: "Svalbard and Jan Mayen",
		timezone: [],
		search: ["svalbard og jan mayen", "sj", "svalbard and jan mayen islands", "sjm", "svalbard and jan mayen"],
		call: ["4779"],
		currency: ["nok"],
		lang: ["nor"]
	},
	sk: {
		name: "Slovakia",
		timezone: ["+01:00"],
		search: ["slovak republic", "slovensko", "sk", "slovenská republika", "svk", "slovakia"],
		call: ["421"],
		currency: ["eur"],
		lang: ["slk"]
	},
	sl: {
		name: "Sierra Leone",
		timezone: [],
		search: ["republic of sierra leone", "sierra leone", "sl", "sle"],
		call: ["232"],
		currency: ["sll"],
		lang: ["eng"]
	},
	sm: {
		name: "San Marino",
		timezone: [],
		search: [
			"most serene republic of san marino",
			"san marino",
			"sm",
			"republic of san marino",
			"repubblica di san marino",
			"smr"
		],
		call: ["378"],
		currency: ["eur"],
		lang: ["ita"]
	},
	sn: {
		name: "Senegal",
		timezone: ["+00:00"],
		search: ["republic of senegal", "sénégal", "sn", "république du sénégal", "sen", "senegal"],
		call: ["221"],
		currency: ["xof"],
		lang: ["fra"]
	},
	so: {
		name: "Somalia",
		timezone: ["+03:00"],
		search: [
			"federal republic of somalia",
			"الصومال‎‎",
			"soomaaliya",
			"so",
			"aṣ-ṣūmāl",
			"jamhuuriyadda federaalka soomaaliya",
			"jumhūriyyat aṣ-ṣūmāl al-fiderāliyya",
			"som",
			"somalia"
		],
		call: ["252"],
		currency: ["sos"],
		lang: ["ara", "som"]
	},
	sr: {
		name: "Suriname",
		timezone: [],
		search: ["republic of suriname", "suriname", "sr", "sarnam", "sranangron", "republiek suriname", "sur"],
		call: ["597"],
		currency: ["srd"],
		lang: ["nld"]
	},
	ss: {
		name: "South Sudan",
		timezone: [],
		search: ["republic of south sudan", "south sudan", "ss", "ssd"],
		call: ["211"],
		currency: ["ssp"],
		lang: ["eng"]
	},
	st: {
		name: "São Tomé and Príncipe",
		timezone: [],
		search: [
			"democratic republic of são tomé and príncipe",
			"são tomé e príncipe",
			"st",
			"sao tome and principe",
			"república democrática de são tomé e príncipe",
			"stp",
			"são tomé and príncipe"
		],
		call: ["239"],
		currency: ["std"],
		lang: ["por"]
	},
	sv: {
		name: "El Salvador",
		timezone: ["-06:00"],
		search: ["republic of el salvador", "el salvador", "sv", "república de el salvador", "slv"],
		call: ["503"],
		currency: ["svc", "usd"],
		lang: ["spa"]
	},
	sx: {
		name: "Sint Maarten",
		timezone: [],
		search: ["sint maarten", "saint-martin", "sx", "sint maarten (dutch part)", "sxm"],
		call: ["1721"],
		currency: ["ang"],
		lang: ["eng", "fra", "nld"]
	},
	sy: {
		name: "Syria",
		timezone: ["+02:00"],
		search: ["syrian arab republic", "سوريا", "sy", "al-jumhūrīyah al-ʻarabīyah as-sūrīyah", "syr", "syria"],
		call: ["963"],
		currency: ["syp"],
		lang: ["ara"]
	},
	sz: {
		name: "Eswatini",
		timezone: [],
		search: [
			"kingdom of eswatini",
			"eswatini",
			"sz",
			"swaziland",
			"weswatini",
			"swatini",
			"ngwane",
			"umbuso weswatini",
			"swz"
		],
		call: ["268"],
		currency: ["szl"],
		lang: ["eng", "ssw"]
	},
	tc: {
		name: "Turks and Caicos Islands",
		timezone: [],
		search: ["turks and caicos islands", "tc", "tca"],
		call: ["1649"],
		currency: ["usd"],
		lang: ["eng"]
	},
	td: {
		name: "Chad",
		timezone: [],
		search: ["republic of chad", "تشاد‎", "tchad", "td", "république du tchad", "tcd", "chad"],
		call: ["235"],
		currency: ["xaf"],
		lang: ["ara", "fra"]
	},
	tf: {
		name: "French Southern and Antarctic Lands",
		timezone: [],
		search: [
			"territory of the french southern and antarctic lands",
			"terres australes et antarctiques françaises",
			"tf",
			"french southern territories",
			"atf",
			"french southern and antarctic lands"
		],
		call: [],
		currency: ["eur"],
		lang: ["fra"]
	},
	tg: {
		name: "Togo",
		timezone: [],
		search: ["togolese republic", "togo", "tg", "togolese", "république togolaise", "tgo"],
		call: ["228"],
		currency: ["xof"],
		lang: ["fra"]
	},
	th: {
		name: "Thailand",
		timezone: ["+07:00"],
		search: [
			"kingdom of thailand",
			"ประเทศไทย",
			"th",
			"prathet",
			"thai",
			"ราชอาณาจักรไทย",
			"ratcha anachak thai",
			"tha",
			"thailand"
		],
		call: ["66"],
		currency: ["thb"],
		lang: ["tha"]
	},
	tj: {
		name: "Tajikistan",
		timezone: ["+05:00"],
		search: [
			"republic of tajikistan",
			"таджикистан",
			"тоҷикистон",
			"tj",
			"toçikiston",
			"ҷумҳурии тоҷикистон",
			"çumhuriyi toçikiston",
			"tjk",
			"tajikistan"
		],
		call: ["992"],
		currency: ["tjs"],
		lang: ["rus", "tgk"]
	},
	tk: {
		name: "Tokelau",
		timezone: [],
		search: ["tokelau", "tk", "tkl"],
		call: ["690"],
		currency: ["nzd"],
		lang: ["eng", "smo", "tkl"]
	},
	tl: {
		name: "Timor-Leste",
		timezone: [],
		search: [
			"democratic republic of timor-leste",
			"timor-leste",
			"timór-leste",
			"tl",
			"east timor",
			"república democrática de timor-leste",
			"repúblika demokrátika timór-leste",
			"timór lorosa'e",
			"timor lorosae",
			"tls"
		],
		call: ["670"],
		currency: ["usd"],
		lang: ["por", "tet"]
	},
	tm: {
		name: "Turkmenistan",
		timezone: ["+05:00"],
		search: ["turkmenistan", "туркмения", "türkmenistan", "tm", "tkm"],
		call: ["993"],
		currency: ["tmt"],
		lang: ["rus", "tuk"]
	},
	tn: {
		name: "Tunisia",
		timezone: ["+01:00"],
		search: [
			"tunisian republic",
			"تونس",
			"tn",
			"republic of tunisia",
			"al-jumhūriyyah at-tūnisiyyah",
			"tun",
			"tunisia"
		],
		call: ["216"],
		currency: ["tnd"],
		lang: ["ara"]
	},
	to: {
		name: "Tonga",
		timezone: [],
		search: ["kingdom of tonga", "tonga", "to", "ton"],
		call: ["676"],
		currency: ["top"],
		lang: ["eng", "ton"]
	},
	tr: {
		name: "Turkey",
		timezone: ["+02:00"],
		search: ["republic of turkey", "türkiye", "tr", "turkiye", "türkiye cumhuriyeti", "tur", "turkey"],
		call: ["90"],
		currency: ["try"],
		lang: ["tur"]
	},
	tt: {
		name: "Trinidad and Tobago",
		timezone: ["-04:00"],
		search: ["republic of trinidad and tobago", "trinidad and tobago", "tt", "tto"],
		call: ["1868"],
		currency: ["ttd"],
		lang: ["eng"]
	},
	tv: {
		name: "Tuvalu",
		timezone: [],
		search: ["tuvalu", "tv", "tuv"],
		call: ["688"],
		currency: ["aud"],
		lang: ["eng", "tvl"]
	},
	tw: {
		name: "Taiwan",
		timezone: ["+08:00"],
		search: [
			"republic of china (taiwan)",
			"台灣",
			"tw",
			"táiwān",
			"republic of china",
			"中華民國",
			"zhōnghuá mínguó",
			"chinese taipei",
			"twn",
			"taiwan"
		],
		call: ["886"],
		currency: ["twd"],
		lang: ["zho"]
	},
	tz: {
		name: "Tanzania",
		timezone: [],
		search: [
			"united republic of tanzania",
			"tanzania",
			"tz",
			"tanzania, united republic of",
			"jamhuri ya muungano wa tanzania",
			"tza"
		],
		call: ["255"],
		currency: ["tzs"],
		lang: ["eng", "swa"]
	},
	ua: {
		name: "Ukraine",
		timezone: ["+02:00"],
		search: ["ukraine", "україна", "ua", "ukrayina", "ukr"],
		call: ["380"],
		currency: ["uah"],
		lang: ["ukr"]
	},
	ug: {
		name: "Uganda",
		timezone: [],
		search: ["republic of uganda", "uganda", "ug", "jamhuri ya uganda", "uga"],
		call: ["256"],
		currency: ["ugx"],
		lang: ["eng", "swa"]
	},
	um: {
		name: "United States Minor Outlying Islands",
		timezone: [],
		search: ["united states minor outlying islands", "um", "umi"],
		call: [],
		currency: ["usd"],
		lang: ["eng"]
	},
	us: {
		name: "United States",
		timezone: ["-05:00", "-06:00", "-07:00", "-08:00", "-09:00", "-10:00"],
		search: ["united states of america", "united states", "us", "usa"],
		call: ["1"],
		currency: ["usd"],
		lang: ["eng"]
	},
	uy: {
		name: "Uruguay",
		timezone: ["-03:00"],
		search: ["oriental republic of uruguay", "uruguay", "uy", "república oriental del uruguay", "ury"],
		call: ["598"],
		currency: ["uyu"],
		lang: ["spa"]
	},
	uz: {
		name: "Uzbekistan",
		timezone: ["+05:00"],
		search: [
			"republic of uzbekistan",
			"узбекистан",
			"o‘zbekiston",
			"uz",
			"o‘zbekiston respublikasi",
			"ўзбекистон республикаси",
			"uzb",
			"uzbekistan"
		],
		call: ["998"],
		currency: ["uzs"],
		lang: ["rus", "uzb"]
	},
	va: {
		name: "Vatican City",
		timezone: [],
		search: [
			"vatican city state",
			"vaticano",
			"vaticanæ",
			"va",
			"holy see (vatican city state)",
			"stato della città del vaticano",
			"vat",
			"vatican city"
		],
		call: ["3906698", "379"],
		currency: ["eur"],
		lang: ["ita", "lat"]
	},
	vc: {
		name: "Saint Vincent and the Grenadines",
		timezone: [],
		search: ["saint vincent and the grenadines", "vc", "vct"],
		call: ["1784"],
		currency: ["xcd"],
		lang: ["eng"]
	},
	ve: {
		name: "Venezuela",
		timezone: ["-04:00"],
		search: [
			"bolivarian republic of venezuela",
			"venezuela",
			"ve",
			"venezuela, bolivarian republic of",
			"república bolivariana de venezuela",
			"ven"
		],
		call: ["58"],
		currency: ["vef"],
		lang: ["spa"]
	},
	vi: {
		name: "United States Virgin Islands",
		timezone: [],
		search: [
			"virgin islands of the united states",
			"united states virgin islands",
			"vi",
			"virgin islands, u.s.",
			"vir"
		],
		call: ["1340"],
		currency: ["usd"],
		lang: ["eng"]
	},
	vn: {
		name: "Vietnam",
		timezone: ["+07:00"],
		search: [
			"socialist republic of vietnam",
			"việt nam",
			"vn",
			"cộng hòa xã hội chủ nghĩa việt nam",
			"viet nam",
			"vnm",
			"vietnam"
		],
		call: ["84"],
		currency: ["vnd"],
		lang: ["vie"]
	},
	vu: {
		name: "Vanuatu",
		timezone: [],
		search: ["republic of vanuatu", "vanuatu", "vu", "ripablik blong vanuatu", "république de vanuatu", "vut"],
		call: ["678"],
		currency: ["vuv"],
		lang: ["bis", "eng", "fra"]
	},
	wf: {
		name: "Wallis and Futuna",
		timezone: [],
		search: [
			"territory of the wallis and futuna islands",
			"wallis et futuna",
			"wf",
			"territoire des îles wallis et futuna",
			"wlf",
			"wallis and futuna"
		],
		call: ["681"],
		currency: ["xpf"],
		lang: ["fra"]
	},
	ws: {
		name: "Samoa",
		timezone: [],
		search: ["independent state of samoa", "samoa", "sāmoa", "ws", "malo saʻoloto tutoʻatasi o sāmoa", "wsm"],
		call: ["685"],
		currency: ["wst"],
		lang: ["eng", "smo"]
	},
	ye: {
		name: "Yemen",
		timezone: ["+03:00"],
		search: ["republic of yemen", "اليَمَن", "ye", "yemeni republic", "al-jumhūriyyah al-yamaniyyah", "yem", "yemen"],
		call: ["967"],
		currency: ["yer"],
		lang: ["ara"]
	},
	yt: {
		name: "Mayotte",
		timezone: [],
		search: ["department of mayotte", "mayotte", "yt", "département de mayotte", "myt"],
		call: ["262"],
		currency: ["eur"],
		lang: ["fra"]
	},
	za: {
		name: "South Africa",
		timezone: ["+02:00"],
		search: [
			"republic of south africa",
			"south africa",
			"sewula afrika",
			"afrika-borwa",
			"afrika borwa",
			"ningizimu afrika",
			"aforika borwa",
			"afrika dzonga",
			"afurika tshipembe",
			"mzantsi afrika",
			"za",
			"rsa",
			"suid-afrika",
			"zaf"
		],
		call: ["27"],
		currency: ["zar"],
		lang: ["afr", "eng", "nbl", "nso", "sot", "ssw", "tsn", "tso", "ven", "xho", "zul"]
	},
	zm: {
		name: "Zambia",
		timezone: [],
		search: ["republic of zambia", "zambia", "zm", "zmb"],
		call: ["260"],
		currency: ["zmw"],
		lang: ["eng"]
	},
	zw: {
		name: "Zimbabwe",
		timezone: ["+02:00"],
		search: ["republic of zimbabwe", "zimbabwe", "zw", "zwe"],
		call: ["263"],
		currency: ["zwl"],
		lang: ["bwg", "eng", "kck", "khi", "ndc", "nde", "nya", "sna", "sot", "toi", "tsn", "tso", "ven", "xho", "zib"]
	}
};
