load("//tools/bazel_build/rules:bdl.bzl", "bdl_library")

bdl_library(
    name = "file_descriptor",
    srcs = [
        "file_descriptor.bdl",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/components/posix/io/impl:file_descriptor"
    ]
)
