load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "substitutions",
    srcs = [
        "substitutions.py",
    ],
    deps = [
        "//python/bzd/template2",
    ],
)

py_test(
    name = "control",
    srcs = [
        "control.py",
    ],
    deps = [
        "//python/bzd/template2",
    ],
)
