load("@bzd_lib//config:defs.bzl", "bzd_config_default")

bzd_config_default(
    name = "config",
    srcs = [
        "config.default.json",
    ],
    visibility = [
        "//apps/accounts/example:__subpackages__",
    ],
)
