load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "stub",
    hdrs = [
        "stub.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/core/logger/backend",
    ],
)
