load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "associate_scope",
    hdrs = [
        "associate_scope.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/container:tuple",
        "//cc/bzd/type_traits/iterator:begin",
        "//cc/bzd/type_traits/iterator:end",
    ],
)
