load("@bzd_lib//config:defs.bzl", "bzd_config_default")
load("@bzd_rules_nodejs//nodejs:defs.bzl", "bzd_nodejs_library")
load("//nodejs/bazel:defs.bzl", "bzd_nodejs_config")

bzd_config_default(
    name = "config",
    srcs = [
        "config.default.json",
    ],
    visibility = [
        "//visibility:public",
    ],
)

bzd_nodejs_config(
    name = "config_nodejs",
    config = ":config",
    expose = {
        "application": "configApplication",
        "authentication": "configAuthentication",
    },
)

bzd_nodejs_library(
    name = "backend",
    srcs = [
        "backend.js",
    ],
    packages = [
        "@nodejs_deps//:commander",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":config_nodejs",
        "//apps/accounts/authentication:server",
        "//nodejs/core:cache",
        "//nodejs/core:exception",
        "//nodejs/core:log",
        "//nodejs/core/authentication:server",
        "//nodejs/core/http:server",
        "//nodejs/core/http/mock:server",
        "//nodejs/core/mcp:server",
        "//nodejs/core/rest:server",
        "//nodejs/core/services",
        "//nodejs/core/statistics",
        "//nodejs/core/statistics:provider_process",
        "//nodejs/core/websocket:server",
        "//nodejs/vue/components/logger/backend/memory",
    ],
)

bzd_nodejs_library(
    name = "frontend",
    srcs = [
        "application.vue",
        "frontend.js",
        "views/404.vue",
        "views/logger.vue",
        "views/services.vue",
        "views/statistics.vue",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        ":config_nodejs",
        "//apps/accounts/authentication:client",
        "//nodejs:icons",
        "//nodejs:vue",
        "//nodejs/core:exception",
        "//nodejs/core:log",
        "//nodejs/core/services:frontend",
        "//nodejs/core/statistics:frontend",
        "//nodejs/styles/default",
        "//nodejs/vue:authentication",
        "//nodejs/vue:metadata",
        "//nodejs/vue:notification",
        "//nodejs/vue:rest",
        "//nodejs/vue:websocket",
        "//nodejs/vue/components/layout",
        "//nodejs/vue/components/layout:component",
        "//nodejs/vue/components/logger/frontend",
        "//nodejs/vue/components/menu:entry",
        "//nodejs/vue/directives:loading",
        "//nodejs/vue/directives:tooltip",
        "//nodejs/vue/router",
    ],
)
