load("@bzd_bdl//:defs.bzl", "bdl_library")
load("@rules_rust//rust:defs.bzl", "rust_library")
load("//rust:defs.bzl", "rust_test")

rust_library(
    name = "stream_impl",
    srcs = [
        "stream_impl.rs",
    ],
)

bdl_library(
    name = "interface",
    srcs = [
        "interface.bdl",
    ],
    implementation = {
        "rust": ":stream_impl",
    },
)

rust_library(
    name = "implementation",
    srcs = [
        "implementation.rs",
    ],
    deps = [
        ":interface",
        "//rust/bzd",
    ],
)

rust_test(
    name = "implementation_test",
    crate = ":implementation",
)
