load("@bzd_rules_nodejs//nodejs:defs.bzl", "bzd_nodejs_test")

bzd_nodejs_test(
    name = "runfiles",
    srcs = [
        "runfiles.js",
    ],
    args = [
        "--data",
        "$(rlocationpath :data.txt)",
    ],
    data = [
        ":data.txt",
    ],
    main = "runfiles.js",
    deps = [
        "//nodejs/utils:runfiles",
    ],
)
