load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "format",
    srcs = [
        "main.cpp",
    ],
    deps = [
        "//platform:bzd",
        "@esp32_xtensa_sdk_2020.01.14//:sdk"
    ],
)
