[tool.yapf]
based_on_style = "pep8"
use_tabs = true
continuation_align_style = "SPACE"
column_limit = 120
blank_line_before_nested_class_or_def = true
indent_dictionary_value = true

[tool.mypy]
python_version = "3.11"
exclude = [
    "rules_python_entry_point_*.py",
]

[[tool.mypy.overrides]]
module = [
    "psutil.*",
    "yfinance.*",
    "requests.*",
    "pandas.*",
    "bs4.*",
    "soupsieve.*",
    "numpy.*",
    "html5lib.*",
    "urllib3.*",
    "multitasking.*",
    "dateutil.*",
    "lxml.*",
    "pytz.*",
    "six.*",
    "frozendict.*",
    "webencodings.*",
    "appdirs.*",
    "charset_normalizer.*",
    "serial.*",
    "paramiko.*",
    "cryptography.*",
    "nacl.*",
    "bcrypt.*",
    "codespell.*",
    "chardet.*",
    "elftools.*",
    "yaml.*",
    "octodns.*",
    "idna.*",
    "natsort.*",
    "fqdn.*",
]
ignore_errors = true
