exports_files(["vite.config.js"])

filegroup(
    name = "metadata_json",
    srcs = ["metadata.json"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "webpack_config_template",
    srcs = ["webpack.config.cjs.template"],
    visibility = ["//visibility:public"],
)
