load("@bzd_lib//embed:defs.bzl", "bzd_embed")

bzd_embed(
    name = "reset_password",
    format = "mjs-text",
    input = "reset_password.html",
    output = "reset_password.mjs",
    visibility = ["//apps/accounts/backend:__pkg__"],
)
