load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "types",
    hdrs = [
        "types.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/container",
        "//cc/bzd/core/logger",
        "//cc/bzd/platform/backend:setter",
    ],
)
