load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary")

exports_files([
    "config.job_executor.json",
])

py_binary(
    name = "dyson_fetch",
    srcs = [
        "dyson_fetch.py",
    ],
    visibility = [
        "//apps/job_executor:__subpackages__",
        "//deployment:__subpackages__",
    ],
    deps = [
        requirement("paho-mqtt"),
    ],
)
