load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "comparison",
    hdrs = [
        "equal_to.hh",
        "greater_equal.hh",
        "greater.hh",
        "less_equal.hh",
        "less.hh",
        "not_equal_to.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/platform:types",
    ],
)
