load("@bzd_bdl//:defs.bzl", "bdl_library")
load("@rules_rust//rust:defs.bzl", "rust_library")
load("//rust:defs.bzl", "rust_binary")

bdl_library(
    name = "interface",
    srcs = [
        "interface.bdl",
    ],
)

rust_library(
    name = "user",
    srcs = [
        "user.rs",
    ],
    deps = [
        ":interface",
        "//rust/bzd",
        "//rust/libs/std",
    ],
)

rust_library(
    name = "component",
    srcs = [
        "component.rs",
    ],
    deps = [
        "//rust/bzd",
    ],
)

rust_binary(
    name = "composition",
    srcs = [
        "composition.rs",
    ],
    deps = [
        ":component",
        ":user",
        "//rust/bzd",
    ],
)
