load("@bzd_bdl//:defs.bzl", "bdl_library")
load("@rules_rust//rust:defs.bzl", "rust_library")
load("//rust:defs.bzl", "rust_binary")

bdl_library(
    name = "interface",
    srcs = [
        "interface.bdl",
    ],
)

rust_library(
    name = "person",
    srcs = [
        "person.rs",
    ],
    deps = [
        ":interface",
        "//rust/bzd",
        "//rust/libs/std",
    ],
)

rust_library(
    name = "child",
    srcs = [
        "child.rs",
    ],
    deps = [
        ":interface",
        "//rust/bzd",
        "//rust/libs/std",
    ],
)

rust_library(
    name = "parent",
    srcs = [
        "parent.rs",
    ],
    deps = [
        ":interface",
        "//rust/bzd",
        "//rust/libs/std",
    ],
)

rust_binary(
    name = "composition",
    srcs = [
        "composition.rs",
    ],
    deps = [
        ":child",
        ":parent",
        "//rust/bdl/generator/impl/adapter:component",
        "//rust/bzd",
    ],
)
