use component::{Lifecycle, Wrapper};
use core::cell::UnsafeCell;

// --- These are for test purpose

// This struct should be autogenerated.
struct UserContext {
    username: &'static str,
    age: u32,
}

// The component implementation, written once per component type.
struct User {
    context: UserContext,
    // Internal variables
    nb_time_printed: u32,
}

impl User {
    fn new(context: UserContext) -> Self {
        Self {
            context,
            nb_time_printed: 1,
        }
    }

    fn print_info(&mut self) {
        println!(
            "User: {}, Age: {}, Printed: {} time(s)",
            self.context.username, self.context.age, self.nb_time_printed
        );
        self.nb_time_printed += 1;
    }
}

// ---- Registry

// Safety: Only safe in single-threaded environments.
struct LocalStatic<T>(UnsafeCell<Option<T>>);
unsafe impl<T> Sync for LocalStatic<T> {}

impl<T> LocalStatic<T> {
    const fn new() -> Self {
        Self(UnsafeCell::new(None))
    }

    #[allow(clippy::mut_from_ref)] // Sound because access is exclusive and single-threaded.
    fn get_mut_or_init(&self, init: impl FnOnce() -> T) -> &mut T {
        // Safety: The returned mutable reference is exclusive, a new one is only
        // taken once the previous one is no longer in use.
        let cell = unsafe { &mut *self.0.get() };
        cell.get_or_insert_with(init)
    }
}

struct UserEntryAlpha {
    instance: User,
}

impl Lifecycle for UserEntryAlpha {
    async fn init(&mut self) -> Result<(), bzd::base::error::Error> {
        println!("[alpha] init");
        Ok(())
    }

    async fn shutdown(&mut self) -> Result<(), bzd::base::error::Error> {
        println!("[alpha] shutdown");
        Ok(())
    }
}

// One registry function per composition entry, it creates and returns mutable
// access to the component instance.
fn registry_user_alpha() -> &'static mut User {
    static COMPONENT: LocalStatic<Wrapper<UserEntryAlpha>> = LocalStatic::new();
    &mut COMPONENT
        .get_mut_or_init(|| {
            Wrapper::new(UserEntryAlpha {
                instance: User::new(UserContext {
                    age: 28,
                    username: "Alex",
                }),
            })
        })
        .instance
}

struct UserEntryBeta {
    instance: User,
}

impl Lifecycle for UserEntryBeta {
    async fn init(&mut self) -> Result<(), bzd::base::error::Error> {
        println!("[beta] init");
        Ok(())
    }

    async fn shutdown(&mut self) -> Result<(), bzd::base::error::Error> {
        println!("[beta] shutdown");
        Ok(())
    }
}

fn registry_user_beta() -> &'static mut User {
    static COMPONENT: LocalStatic<Wrapper<UserEntryBeta>> = LocalStatic::new();
    &mut COMPONENT
        .get_mut_or_init(|| {
            Wrapper::new(UserEntryBeta {
                instance: User::new(UserContext {
                    age: 42,
                    username: "Bob",
                }),
            })
        })
        .instance
}

fn main() {
    let user_alpha = registry_user_alpha();
    let user_beta = registry_user_beta();
    user_alpha.print_info();
    user_alpha.print_info();
    user_beta.print_info();
}
