use component::{Lifecycle, Wrapper};
use core::cell::UnsafeCell;

// --- These are for test purpose

// This struct should be autogenerated.
struct UserContext {
    username: &'static str,
    age: u32,
    sibling: Option<&'static User>,
}

// The component implementation, written once per component type.
struct User {
    context: UserContext,
    // Internal variables
    nb_time_printed: u32,
}

impl User {
    fn new(context: UserContext) -> Self {
        Self {
            context,
            nb_time_printed: 1,
        }
    }

    fn print_info(&mut self) {
        print!(
            "User: {}, Age: {}, Printed: {} time(s)",
            self.context.username, self.context.age, self.nb_time_printed
        );
        if let Some(sibling) = self.context.sibling {
            println!(", Sibling: {}", sibling.context.username);
        } else {
            println!(", No sibling");
        }
        self.nb_time_printed += 1;
    }
}

// ---- Registry

// Safety: Only safe in single-threaded environments.
struct LocalStatic<T>(UnsafeCell<Option<T>>);
unsafe impl<T> Sync for LocalStatic<T> {}

impl<T> LocalStatic<T> {
    const fn new() -> Self {
        Self(UnsafeCell::new(None))
    }

    #[allow(clippy::mut_from_ref)] // Sound because access is exclusive and single-threaded.
    fn get_mut_or_init(&self, init: impl FnOnce() -> T) -> &mut T {
        // Safety: The returned mutable reference is exclusive, a new one is only
        // taken once the previous one is no longer in use.
        let cell = unsafe { &mut *self.0.get() };
        cell.get_or_insert_with(init)
    }
}

struct UserEntryAlpha {
    instance: User,
}

impl Lifecycle for UserEntryAlpha {
    async fn init(&mut self) -> Result<(), bzd::base::error::Error> {
        println!("[alex] init");
        Ok(())
    }

    async fn shutdown(&mut self) -> Result<(), bzd::base::error::Error> {
        println!("[alex] shutdown");
        Ok(())
    }
}

// One registry function per composition entry, it creates and returns mutable
// access to the component wrapper.
fn registry_user_alpha() -> &'static mut Wrapper<UserEntryAlpha> {
    static COMPONENT: LocalStatic<Wrapper<UserEntryAlpha>> = LocalStatic::new();
    COMPONENT.get_mut_or_init(|| {
        Wrapper::new(UserEntryAlpha {
            instance: User::new(UserContext {
                age: 28,
                username: "Alex",
                sibling: Some(&registry_user_beta().instance),
            }),
        })
    })
}

struct UserEntryBeta {
    instance: User,
}

impl Lifecycle for UserEntryBeta {
    async fn init(&mut self) -> Result<(), bzd::base::error::Error> {
        println!("[bob] init");
        Ok(())
    }

    async fn shutdown(&mut self) -> Result<(), bzd::base::error::Error> {
        println!("[bob] shutdown");
        Ok(())
    }
}

fn registry_user_beta() -> &'static mut Wrapper<UserEntryBeta> {
    static COMPONENT: LocalStatic<Wrapper<UserEntryBeta>> = LocalStatic::new();
    COMPONENT.get_mut_or_init(|| {
        Wrapper::new(UserEntryBeta {
            instance: User::new(UserContext {
                age: 42,
                username: "Bob",
                sibling: None,
            }),
        })
    })
}

fn block_on<F: core::future::Future>(future: F) -> F::Output {
    use core::task::{Context, Poll, RawWaker, RawWakerVTable, Waker};

    fn clone(_: *const ()) -> RawWaker {
        RawWaker::new(core::ptr::null(), &VTABLE)
    }
    fn noop(_: *const ()) {}
    static VTABLE: RawWakerVTable = RawWakerVTable::new(clone, noop, noop, noop);

    let mut future = core::pin::pin!(future);
    // Safety: The waker never dereferences its data pointer.
    let waker = unsafe { Waker::from_raw(RawWaker::new(core::ptr::null(), &VTABLE)) };
    let mut context = Context::from_waker(&waker);
    loop {
        if let Poll::Ready(result) = future.as_mut().poll(&mut context) {
            return result;
        }
    }
}

fn main() -> Result<(), bzd::base::error::Error> {
    let user_alpha = registry_user_alpha();
    let user_beta = registry_user_beta();

    block_on(user_alpha.init())?;
    block_on(user_beta.init())?;

    user_alpha.instance.print_info();
    user_alpha.instance.print_info();
    user_beta.instance.print_info();

    block_on(user_alpha.shutdown())?;
    block_on(user_beta.shutdown())?;

    Ok(())
}
