use component::{Component, Wrapper};
use core::cell::OnceCell;

// --- These are for test purpose

// This struct should be autogenerated.
struct UserContext {
    username: &'static str,
    age: u32,
}

struct User {
    context: UserContext,
    // Internal variables
    nb_time_printed: u32,
}

impl User {
    fn new(context: UserContext) -> Self {
        Self {
            context,
            nb_time_printed: 1,
        }
    }

    fn print_info(&mut self) {
        println!(
            "User: {}, Age: {}, printed: {} time(s)",
            self.context.username, self.context.age, self.nb_time_printed
        );
        self.nb_time_printed += 1;
    }
}

// ---- Registry

/*
// Safety: Only safe in single-threaded environments
struct LocalStatic<T>(OnceCell<T>);
unsafe impl<T> Sync for LocalStatic<T> {}

fn registry_user() -> &'static Wrapper<ComponentUser> {
    static COMPONENT: LocalStatic<Wrapper<ComponentUser>> = LocalStatic(OnceCell::new());

    COMPONENT.0.get_or_init(|| {

        let instance = User {
            age: 28,
            username: "Alex",
        };

        Wrapper::new(ComponentUser {
            instance: instance,
        })
    })
}
*/

fn main() {
    let user_context = UserContext {
        age: 28,
        username: "Alex",
    };
    let mut user = Wrapper::new(Component {
        instance: User::new(user_context),
        on_init: || async { Ok::<(), bzd::base::error::Error>(()) },
        on_shutdown: || async { Ok::<(), bzd::base::error::Error>(()) },
    });

    user.instance.print_info();
    user.instance.print_info();

    println!("hello");
}
