load("@bzd_lib//config:defs.bzl", "bzd_config")

bzd_config(
    name = "config",
    srcs = [
        "config.default.json",
    ],
    visibility = [
        "//apps/artifacts/plugins/fs/release:__subpackages__",
        "//deployment:__subpackages__",
    ],
)
