load("//tools/bazel_build/rules:cc.bzl", "bzd_cc_test")

bzd_cc_test(
    name = "tests",
    srcs = [
        "integral.cc",
    ],
    deps = [
        "//cc/bzd/test",
        "//cc/bzd/utility/string/from_string:integral",
    ],
)
