load("@//tools/bzd:defs.bzl", "bzd_cc_library")

cc_library(
    name = "port",
    srcs = [":port.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//platform:bzd_core",
    ],
)
