name: "Run opencode"
description: "Runs the opencode agent"

inputs:
    prompt:
        description: "The prompt to be used for the agent."
        required: true
    agent:
        description: "The agent to be using."
        required: false
        default: "build"

outputs:
    response_file:
        description: "Path of the raw agent response."
        value: "/tmp/agent-response.txt"

runs:
    using: "composite"
    steps:
        - name: "Opencode version"
          shell: bash
          run: |
              opencode --version

        - name: "Run opencode"
          shell: bash
          env:
              PROMPT: ${{ inputs.prompt }}
              AGENT: ${{ inputs.agent }}
          run: |
              set -euo pipefail
              echo  "==== prompt ================================================="
              echo "$PROMPT"
              echo  "==== processing ============================================="
              #bzd-lease opencode run --dangerously-skip-permissions --agent "$AGENT" "$PROMPT" > /tmp/agent-response.txt || {
              #  echo "==== Opencode failed, dumping last log ======================"
              #  tail -n 100 "$(ls -t ~/.local/share/opencode/log/*.log 2>/dev/null | head -n 1)" || echo "No log found"
              #  exit 1
              #}
              echo "{\"vulnerability_found\":true,\"title\":"test",\"severity\": \"Critical\"}" > /tmp/agent-response.txt
              echo  "==== response ==============================================="
              cat /tmp/agent-response.txt
