name: "Run opencode"
description: "Runs the opencode agent"

inputs:
    prompt:
        description: "The prompt to be used for the agent."
        required: true
    agent:
        description: "The agent to be using."
        required: false
        default: "build"

outputs:
    response_file:
        description: "Path of the raw agent response."
        value: "/tmp/agent-response.txt"

runs:
    using: "composite"
    steps:
        - name: "Opencode version"
          shell: bash
          run: |
              opencode --version

        - name: "Run opencode"
          shell: bash
          env:
              PROMPT: ${{ inputs.prompt }}
              AGENT: ${{ inputs.agent }}
          run: |
              set -euo pipefail

              ./tools/bazel run //apps/utils/agent -- --output /tmp/agent-response.txt --agent "$AGENT" "$PROMPT"

              echo  "==== response ==============================================="
              cat /tmp/agent-response.txt
