load("@bzd_lib//config:defs.bzl", "bzd_config_default")
load("@bzd_rules_nodejs//nodejs:defs.bzl", "bzd_nodejs_oci_binary")
load("//nodejs/bazel:defs.bzl", "bzd_nodejs_config")

exports_files([
    "api.v1.json",
])

bzd_config_default(
    name = "config",
    srcs = [
        "config.default.json",
    ],
    visibility = [
        "//deployment:__subpackages__",
    ],
)

bzd_nodejs_config(
    name = "config_nodejs",
    config = ":config",
    expose = {
        "facebookAppId": "configFacebookAppId",
        "googleCaptchaSiteKey": "configGoogleCaptchaSiteKey",
        "googleClientId": "configGoogleClientId",
        "url": "configUrl",
    },
    visibility = [
        ":__subpackages__",
    ],
)

bzd_nodejs_oci_binary(
    name = "accounts",
    binary = "//apps/accounts/backend",
    cmd = [
        "--static",
        "apps/accounts/frontend/frontend.bundle",
    ],
    tags = ["manual"],
    visibility = [
        "//deployment:__subpackages__",
    ],
)
