load("//tools/bazel_build/rules:cc.bzl", "bzd_cc_library")

bzd_cc_library(
    name = "serialization",
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/core/serialization/types:floating_point",
        "//cc/bzd/core/serialization/types:integral",
    ],
)
