#!/usr/bin/env python3

import argparse
import os
import pathlib
import platform
import urllib.request
import shutil
import stat
import struct
import subprocess
import sys
import ssl

def processRun(args) -> None:
	"""Execute a process and exit if it fails."""

	result = subprocess.run(args)
	if result.returncode != 0:
		sys.exit(result.returncode)

def getOSAndArchitecture() -> str:
	"""Get the OS architecture identifier."""

	# Identify the bit width.
	bitSize = str(8 * struct.calcsize("P"))

	# Identify the architecture.
	machine = "unknown_"
	machineStr = platform.machine().lower()
	if any(x in machineStr for x in ("amd", "x86", "i386", "i486", "i586", "i686")):
		machine = "x86_"
	elif any(x in machineStr for x in ("aarch", "arm")):
		machine = "arm"

	# Identify the operating system.
	os = "unknown"
	if sys.platform.startswith("linux"):
		os = "linux"
	elif sys.platform.startswith("win") or sys.platform.startswith("cygwin"):
		os = "windows"
	elif sys.platform.startswith("darwin"):
		os = "darwin"

	return f"{os}_{machine}{bitSize}"

if __name__== "__main__":

	parser = argparse.ArgumentParser()
	parser.add_argument("command", nargs="?", default=None)
	args, unknown = parser.parse_known_args()

	# Build the full path of bazelisk
	osAndArchitecture = getOSAndArchitecture()
	bazelDirectory = pathlib.Path(__file__).resolve().parent
	bazeliskPath = bazelDirectory / f"bazelisk_{osAndArchitecture}"

	# If bazel is not installed / available
	if not bazeliskPath.exists():

		# Check the bazename of bazelisk
		OSAndArchitectureToBasename = {
			"darwin_x86_64": "bazelisk-darwin-amd64",
			"darwin_arm64": "bazelisk-darwin-arm64",
			"linux_x86_64": "bazelisk-linux-amd64",
			"linux_arm64": "bazelisk-linux-arm64",
			"windows_x86_64": "bazelisk-windows-amd64.exe"
		}
		basename = OSAndArchitectureToBasename[osAndArchitecture]

		url = "https://github.com/bazelbuild/bazelisk/releases/download/v1.20.0/{}".format(basename)
		print(f"No bazel binary detected, downloading bazelisk from {url}...", flush=True)
		ctx = ssl.create_default_context()
		ctx.check_hostname = False
		ctx.verify_mode = ssl.CERT_NONE
		with urllib.request.urlopen(url, context=ctx) as response, open(bazeliskPath, "wb") as f:
			shutil.copyfileobj(response, f)

		# Set permissions and update bazel binary path
		st = bazeliskPath.stat()
		bazeliskPath.chmod(st.st_mode | stat.S_IEXEC)

	try:
		# Forward commands to the real bazel
		processRun([bazeliskPath] + sys.argv[1:])

		# If this script is called by the wrapper, ignore
		if "BAZELISK_SKIP_WRAPPER" in os.environ:
			sys.exit(0)

		# Generate the coverage report
		if args.command == "coverage":
			processRun([bazeliskPath, "run", "//tools/coverage"])

	# Gracefully handle keyboard interrupts.
	except KeyboardInterrupt:
		print("<<< Keyboard Interrupt >>> ", file=sys.stderr)
		sys.exit(1)
