#!/usr/bin/python3
# -*- coding: iso-8859-1 -*-

import argparse
import os
import sys
import subprocess
import urllib.request
import stat
import shutil

if __name__== "__main__":

	parser = argparse.ArgumentParser()
	parser.add_argument("command", nargs="?", default=None)
	args, unknown = parser.parse_known_args()

	bazelDirectory = os.path.dirname(os.path.realpath(__file__))
	workspaceDirectory = os.path.dirname(bazelDirectory)
	bazeliskPath = os.path.join(bazelDirectory, "bazelisk")

	# If bazel is not installed / available
	if not os.path.exists(bazeliskPath):
		url = "https://github.com/bazelbuild/bazelisk/releases/download/v1.5.0/bazelisk-linux-amd64"
		print("No bazel binary detected, downloading bazelisk from {}...".format(url))
		with urllib.request.urlopen(url) as response, open(bazeliskPath, "wb") as f:
			shutil.copyfileobj(response, f)

		# Set permissions and update bazel binary path
		st = os.stat(bazeliskPath)
		os.chmod(bazeliskPath, st.st_mode | stat.S_IEXEC)

	# Forward commands to the real bazel
	subprocess.run([bazeliskPath] + sys.argv[1:])

	# Generate the coverage report
	if args.command == "coverage":
		subprocess.run([bazeliskPath, "run", "//tools/coverage:report", "--",
				"--show-details",
				"--sort",
				"--function-coverage",
				"--output-directory",
				"bazel-out/coverage",
				"bazel-out/_coverage/_coverage_report.dat"])
		print("Coverage report: {}".format(os.path.join(workspaceDirectory, "bazel-out/coverage/index.html")))
