load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "composition",
    srcs = [
        "composition.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bdl/generator/impl:visitor",
    ],
)

py_binary(
    name = "library",
    srcs = [
        "library.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bdl/generator/impl:visitor",
    ],
)
