py_library(
    name = "format",
    srcs = [
        "format.py",
    ],
    deps = [
        "//cc/bdl/generator/impl:visitor"
    ],
    visibility = ["//visibility:public"]
)

py_library(
    name = "composition",
    srcs = [
        "composition.py",
    ],
    deps = [
        "//cc/bdl/generator/impl:visitor"
    ],
    visibility = ["//visibility:public"]
)
