load("//tools/bazel_build/rules:cc.bzl", "bzd_cc_library")

bzd_cc_library(
    name = "to_string",
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/utility/pattern/formatter/to_string:boolean",
        "//cc/bzd/utility/pattern/formatter/to_string:floating_point",
        "//cc/bzd/utility/pattern/formatter/to_string:integral",
        "//cc/bzd/utility/pattern/formatter/to_string:pattern",
        "//cc/bzd/utility/pattern/formatter/to_string:pointer",
        "//cc/bzd/utility/pattern/formatter/to_string:string",
    ],
)

bzd_cc_library(
    name = "to_stream",
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/utility/pattern/formatter/to_stream:boolean",
        "//cc/bzd/utility/pattern/formatter/to_stream:floating_point",
        "//cc/bzd/utility/pattern/formatter/to_stream:integral",
        "//cc/bzd/utility/pattern/formatter/to_stream:pattern",
        "//cc/bzd/utility/pattern/formatter/to_stream:pointer",
        "//cc/bzd/utility/pattern/formatter/to_stream:string",
    ],
)
