site_name: Documentation
docs_dir: ../
use_directory_urls: false
repo_name: "bzd"
repo_url: "https://github.com/blaizard/bzd"

nav:
  - Home: README.md
  - BDL:
    - Overview: docs/bdl/overview.md
    - Syntax: docs/bdl/syntax.md
    - Components: docs/bdl/components.md
    - Composition: docs/bdl/composition.md
    - Executors: docs/bdl/executors.md
    - Gateway: docs/bdl/gateway.md
    - System: docs/bdl/system.md
  - Bazel:
    - bdl: docs/api/bazel/bdl.md
    - cc: docs/api/bazel/cc.md
    - docker: docs/api/bazel/docker.md
    - nodejs: docs/api/bazel/nodejs.md
    - nodejs_web: docs/api/bazel/nodejs_web.md
    - package: docs/api/bazel/package.md
  - C++:
    - Layout: cc/README.md
    - Async: cc/bzd/core/async/README.md

theme:
  name: material
  palette:
    primary: "blue grey"
    accent: "light blue"

plugins:
  - exclude:
      glob:
        - bazel-out/*
        - external/*
        - tools/documentation/*

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
