load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "null",
    srcs = [
        "null.cc",
    ],
    hdrs = [
        "null.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/core:clock",
    ],
)
