load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "mutex",
    srcs = ["mutex.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//bzd/logging",
    ],
)

py_library(
    name = "singleton",
    srcs = ["singleton.py"],
    visibility = ["//visibility:public"],
)
