services:
    compiler-explorer:
        image: bazel/tools/docker_images:compiler_explorer
        ports:
        - 10240:10240
        volumes:
        - ../../:/bzd:ro
        - ./c++.local.properties:/compiler-explorer/etc/config/c++.local.properties
version: '3.0'
