version: "3.0"
services:
  compiler-explorer:
    build: .
    ports:
      - "10240:10240"
    volumes:
      - ../../:/bzd
      - ./c++.local.properties:/compiler-explorer/etc/config/c++.local.properties
