package(default_visibility = ["//visibility:public"])

config_setting(
    name = "linux",
    constraint_values = [
        "//tools/bazel.build/platforms/al:linux",
    ],
)

config_setting(
    name = "x86_32",
    constraint_values = [
        "//tools/bazel.build/platforms/isa:x86_32",
    ],
)

config_setting(
    name = "x86_64",
    constraint_values = [
        "//tools/bazel.build/platforms/isa:x86_64",
    ],
)

config_setting(
    name = "linux_x86_64",
    constraint_values = [
        "//tools/bazel.build/platforms/al:linux",
        "//tools/bazel.build/platforms/isa:x86_64",
    ],
)
