load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

def toolchain_fragment_esp32_xtensa_lx6_sdk():
    sdk_package_name = "esp32_xtensa_lx6_sdk_4.0"

    http_archive(
        name = sdk_package_name,
        build_file = "//toolchains/cc/fragments/esp32_xtensa_lx6_sdk:{}.BUILD".format(sdk_package_name),
        urls = [
            "https://github.com/blaizard/bzd-esp32-xtensa-sdk/archive/4.0.zip",
        ],
        strip_prefix = "bzd-esp32-xtensa-sdk-4.0",
        sha256 = "8e9d811df47f1182c672e5e5c88bf2b93ee6df83fee296a601234ff65fb89f2b",
    )

    return {
        "builtin_include_directories": [
            "%package(@{}//)%/include".format(sdk_package_name),
        ],
        "system_directories": [
            "external/{}/include".format(sdk_package_name),
        ],
        "compile_flags": [
            "-MMD",
            "-MP",
            "-DCONFIG_IDF_TARGET_ESP32=1",
        ],
        "linker_dirs": [
            "external/{}/ld".format(sdk_package_name),
            "external/{}/lib".format(sdk_package_name),
        ],
        "link_flags": [
            "-nostdlib",
            "-Wl,--start-group",

            # Linker scripts
            "-Tesp32_out.ld",
            "-Tesp32.project.ld",
            "-Tesp32.peripherals.ld",
            "-Tesp32.rom.ld",
            "-Tesp32.rom.libgcc.ld",
            "-Tesp32.rom.syscalls.ld",
            "-Tesp32.rom.newlib-data.ld",
            "-Tesp32.rom.newlib-funcs.ld",

            # Libraries
            "-lapp_trace",
            "-lapp_update",
            "-lasio",
            "-lbootloader_support",
            "-lbt",
            "-lcbor",
            "-lcoap",
            "-lconsole",
            "-lcxx",
            "-ldriver",
            "-lefuse",
            "-lesp-tls",
            "-lesp32",
            "-lesp_adc_cal",
            "-lesp_common",
            "-lesp_eth",
            "-lesp_event",
            "-lesp_gdbstub",
            "-lesp_http_client",
            "-lesp_http_server",
            "-lesp_https_ota",
            "-lesp_local_ctrl",
            "-lesp_netif",
            "-lesp_ringbuf",
            "-lesp_rom",
            "-lesp_serial_slave_link",
            "-lesp_websocket_client",
            "-lesp_wifi",
            "-lcore",
            "-lrtc",
            "-lnet80211",
            "-lpp",
            "-lsmartconfig",
            "-lcoexist",
            "-lespnow",
            "-lphy",
            "-lmesh",
            "-lespcoredump",
            "-lexpat",
            "-lfatfs",
            "-lfreemodbus",
            "-lfreertos",
            "-lheap",
            "-lidf_test",
            "-ljsmn",
            "-ljson",
            "-llibsodium",
            "-llog",
            "-llwip",
            "-lmain",
            "-lmbedtls",
            "-lmdns",
            "-lmqtt",
            "-lnewlib",
            "-lc",
            "-lm",
            "-lnghttp",
            "-lnvs_flash",
            "-lopenssl",
            "-lperfmon",
            "-lprotobuf-c",
            "-lprotocomm",
            "-lpthread",
            "-lsdmmc",
            "-lsoc",
            "-lspi_flash",
            "-lspiffs",
            "-ltcp_transport",
            "-ltcpip_adapter",
            "-lulp",
            "-lunity",
            "-lvfs",
            "-lwear_levelling",
            "-lwifi_provisioning",
            "-lwpa_supplicant",
            "-lxtensa",
            "-lhal",
            "-lgcc",
            "-lstdc++",
            "-lgcov",
            #"-Wl,--end-group",
            "-fno-rtti",
        ],
        "filegroup_dependencies": [
            "@{}//:files".format(sdk_package_name),
        ],
    }
