load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "bzd",
    visibility = ["//cc:__pkg__"],
    deps = [
        "//cc/bzd/algorithm",
        "//cc/bzd/container",
        "//cc/bzd/core",
        "//cc/bzd/meta",
        "//cc/bzd/type_traits",
        "//cc/bzd/utility",
    ],
)
