load("//tools/bazel_build/rules:cc.bzl", "cc_library")

cc_library(
    name = "bzd",
    visibility = ["//visibility:public"],
    deps = [
        "//cc/bzd/algorithm",
        "//cc/bzd/container",
        "//cc/bzd/core",
        "//cc/bzd/meta",
        "//cc/bzd/platform",
        "//cc/bzd/type_traits",
        "//cc/bzd/utility",
    ],
)
