load("//tools/bazel_build/rules:cc.bzl", "cc_library")

cc_library(
    name = "bootstrap",
    srcs = ["bootstrap.cc"],
    tags = ["manual"],
    visibility = ["//visibility:public"],
    alwayslink = True,
)
