name: CI

on:
    push: {}

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: "11.0"
                  architecture: x64

            - name: "Environment"
              run: |
                  cp tools/ci/github/.bazelrc.local .bazelrc.local
                  export PATH="${PATH}:${GITHUB_WORKSPACE}/bin"
                  ./info.sh

            - name: "[normal] static analysis"
              run: |
                  ./tools/bazel run apps/artifacts/api/python/node:binary -- --uid ci --path github/static_analysis timeit \
                  ./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --output_groups=+metadata --config=dev --config=clang-tidy --config=mypy --platform_suffix=static_analysis

            - name: "[normal] clang prod"
              run: |
                  ./tools/bazel run apps/artifacts/api/python/node:binary -- --uid ci --path github/clang_prod timeit \
                  ./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --output_groups=+metadata --config=clang --config=prod --config=cc --platform_suffix=clang-prod

            - name: "[normal] gcc prod"
              run: |
                  ./tools/bazel run apps/artifacts/api/python/node:binary -- --uid ci --path github/gcc_prod timeit \
                  ./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --output_groups=+metadata --config=gcc --config=prod --config=cc --platform_suffix=gcc-prod

            - name: "[normal] esp32 prod"
              run: |
                  ./tools/bazel run apps/artifacts/api/python/node:binary -- --uid ci --path github/esp32_prod timeit \
                  ./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --output_groups=+metadata --config=esp32 --config=prod --config=cc --platform_suffix=esp32-prod

            - name: "[sanitizer] asan/lsan/ubsan"
              run: |
                  ./tools/bazel run apps/artifacts/api/python/node:binary -- --uid ci --path github/asan_lsan_ubsan timeit \
                  ./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --config=clang --config=cc --config=sanitizer --config=asan --config=lsan --config=ubsan --platform_suffix=clang-asan-lsan-ubsan

            - name: "[sanitizer] tsan"
              run: |
                  ./tools/bazel run apps/artifacts/api/python/node:binary -- --uid ci --path github/tsan timeit \
                  ./tools/bazel test --target_pattern_file=tools/ci/bazel_target_patterns.txt --config=clang --config=cc --config=sanitizer --config=tsan --platform_suffix=clang-tsan

            - name: "[sanitizer] sanitizer"
              run: |
                  ./tools/bazel run apps/artifacts/api/python/node:binary -- --uid ci --path github/sanitizer timeit \
                  ./tools/bazel run :sanitizer -- --check --all

            - name: Build documentation
              run: |
                  ./tools/bazel build docs
                  rm -rfd .dist
                  mkdir -p .dist
                  tar -xf ./bazel-bin/docs/docs.tar -C .dist
            - uses: cpina/github-action-push-to-another-repository@main
              env:
                  SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
              with:
                  source-directory: ".dist"
                  destination-github-username: "blaizard"
                  destination-repository-name: "blaizard.github.io"
                  user-email: doc.publish@blaizard.com
                  target-branch: main
                  target-directory: bzd/

            - name: "Info"
              if: always()
              run: |
                  ./info.sh
