name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0'
        architecture: x64

    - name: Environment
      run: |
        cp tools/ci/github/.bazelrc.local .bazelrc.local
        export PATH="${PATH}:${GITHUB_WORKSPACE}/bin"
        ./tools/bazel --version
        python --version
        java --version
        printenv

    - name: Test
      run: |
        ./tools/bazel test ... --output_groups=default,metadata

    - name: Sanitize
      run: |
        ./sanitize.sh
