name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0'
        architecture: x64

    - name: Environment
      run: |
        cp tools/ci/github/.bazelrc.local .bazelrc.local
        export PATH="${PATH}:${GITHUB_WORKSPACE}/bin"
        ./info.sh

    - name: linux_x86_64_clang
      run: |
        ./tools/bazel test ... --output_groups=default,metadata --config=linux_x86_64_clang

    - name: linux_x86_64_gcc
      run: |
        ./tools/bazel test ... --output_groups=default,metadata --config=linux_x86_64_gcc --config=cc

    - name: esp32_xtensa_lx6_gcc
      run: |
        ./tools/bazel build ... --output_groups=default,metadata --config=esp32_xtensa_lx6_gcc --config=cc

    - name: Sanitize
      run: |
        ./sanitize.sh
