name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0'
        architecture: x64

    - name: "Environment"
      run: |
        cp tools/ci/github/.bazelrc.local .bazelrc.local
        export PATH="${PATH}:${GITHUB_WORKSPACE}/bin"

    - name: "Fetch"
      run: |
        ./tools/bazel fetch //...
        ./tools/bazel run tools/docker_images

    - name: "Info"
      if: always()
      run: |
        ./info.sh

    - name: "[normal] clang-tidy"
      run: |
        ./tools/bazel test ... --output_groups=+metadata --config=dev --config=clang_tidy --platform_suffix=clang_tidy

    - name: "[normal] linux_x86_64_clang prod"
      run: |
        ./tools/bazel test ... --output_groups=+metadata --config=linux_x86_64_clang --config=prod --platform_suffix=linux_x86_64_clang_prod

    - name: "[normal] linux_x86_64_gcc prod"
      run: |
        ./tools/bazel test ... --output_groups=+metadata --config=linux_x86_64_gcc --config=prod --config=cc --platform_suffix=linux_x86_64_gcc_prod

    - name: "[normal] esp32_xtensa_lx6_gcc prod"
      run: |
        ./tools/bazel test ... --output_groups=+metadata --config=esp32_xtensa_lx6_gcc --config=prod --config=cc --platform_suffix=esp32_xtensa_lx6_gcc_prod

    - name: "[sanitizer] asan/lsan"
      run: |
        ./tools/bazel test ... --config=linux_x86_64_clang --config=cc --config=sanitizer --config=asan --config=lsan --platform_suffix=clang_asan_lsan

    - name: "[sanitizer] sanitizer"
      run: |
        ./sanitize.sh

