load("@bzd_bdl//:defs.bzl", "bdl_library")
load("@rules_rust//rust:defs.bzl", "rust_library")

bdl_library(
    name = "interface",
    srcs = [
        "interface.bdl",
    ],
    deps = [
        "//interfaces:stream",
    ],
)

rust_library(
    name = "uart",
    srcs = [
        "uart.rs",
    ],
    crate_name = "rust_components_esp_stream_uart",
    visibility = ["//visibility:public"],
    deps = [
        ":interface",
        "//interfaces:stream",
        "//rust/bzd",
        "//rust/components/esp/hal",
        "@bzd_espressif//hal/rust",
    ],
)
